1. Introduction  
Objective: select best production model  
Decision criteria:  
ROC-AUC  
Recall  
Interpretability  
Inference speed  

2. Load Processed Data  
Same dataset as notebook 02 (no re-cleaning).  

3. Load Baseline Results  
Either:  
Load CSV exported from notebook 02  
OR  
Manually recreate summary table  
This ensures fair comparison.  

4. Ensemble Models Implementation  
Models to test:  
XGBoost  
LightGBM  
AdaBoost  
Stacking Ensemble  
Each model:  
Pipeline  
Imbalance handling  
Hyperparameter tuning (Optuna or GridSearch)  

5. Cross-Validation Results
Stratified 5-fold CV  
Mean ± std ROC-AUC  
Mean Recall  
Plot:  
Boxplot of ROC-AUC across folds  

6. Learning Curves  
For top 2–3 models:  
Training vs validation score  
Detect overfitting  
Saved to /figures  

7. Validation Curves  
One key hyperparameter per model  
Show sensitivity  

8. Feature Importance  
Depending on model:  
Tree-based importance  
SHAP values (preferred)  
Top 10 features  

9. Model Interpretability  
SHAP summary plot  
SHAP force plot (example patient)  
OR  
LIME explanation  
Explain clinical relevance.  

10. Final Model Selection  
Markdown justification:  
Why this model  
Trade-offs  
Comparison vs baseline

---
Define the same dataset use for the best ROC_AUC model from "02_ML_Models.ipynb"

In [1]:
import os
import sys

PROJECT_ROOT = os.path.abspath(os.path.join(os.getcwd(), '..'))
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)
    
from src.models.traditional_ml import (
    load_dataset
)

DATA_DIR = '../data/processed'
FIG_DIR = '../figures/02_ML_Models'
MODELS_DIR = '../models'
RANDOM_STATE = 42

os.makedirs(FIG_DIR, exist_ok=True)
os.makedirs(MODELS_DIR, exist_ok=True)

comparison_traditional = 'model_comparison.csv'
traditional_comparison_df = load_dataset(os.path.join(DATA_DIR, comparison_traditional))

display(traditional_comparison_df.sort_values("test_roc_auc", ascending=False).head())

,dataset_version,model_name,imbalance_method,best_params,cv_best_roc_auc,test_accuracy,test_precision,test_recall,test_f1,test_roc_auc
0,standard_scaled,svm,class_weight,"{""model__C"": 5, ""model__gamma"": ""scale"", ""mode...",0.721043,0.669811,0.252459,0.596899,0.354839,0.689712
1,unscaled,svm,class_weight,"{""model__C"": 5, ""model__gamma"": ""scale"", ""mode...",0.721074,0.668632,0.251634,0.596899,0.354023,0.689712
2,robust_scaled,svm,class_weight,"{""model__C"": 5, ""model__gamma"": ""scale"", ""mode...",0.720986,0.668632,0.251634,0.596899,0.354023,0.689588
7,robust_scaled,svm,smote,"{""model__C"": 5, ""model__gamma"": ""scale"", ""mode...",0.720929,0.650943,0.244648,0.620155,0.350877,0.688887
8,robust_scaled,svm,smote+class_weight,"{""model__C"": 5, ""model__gamma"": ""scale"", ""mode...",0.720929,0.650943,0.244648,0.620155,0.350877,0.688887

In [10]:
best_row = traditional_comparison_df.iloc[0]
best_traditional = f"{best_row.dataset_version}"
train_filepath = os.path.join(DATA_DIR, f'train_{best_traditional}.csv')
test_filepath = os.path.join(DATA_DIR, f'test_{best_traditional}.csv')
train_df = load_dataset(train_filepath)
test_df = load_dataset(test_filepath)

print(f"The data used in the best traditional model is imported for comparison: {best_traditional}.")

The data used in the best traditional model is imported for comparison: unscaled.

In [14]:
"""
Advanced Models & Model Selection - Collaborator 5
Coronary Heart Disease Prediction Project
Timeline: Jan 1-9, 2025
Branch: feature/advanced-models

Final Version: Uses scale_pos_weight and Optuna tuning
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
import json
import pickle
import warnings
warnings.filterwarnings('ignore')

# Model libraries
from sklearn.model_selection import (
    StratifiedKFold, 
    cross_validate,
    learning_curve,
    validation_curve
)
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    roc_auc_score, roc_curve, confusion_matrix, classification_report,
    precision_recall_curve
)

# Ensemble models
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.ensemble import (
    AdaBoostClassifier,
    GradientBoostingClassifier,
    StackingClassifier
)
from sklearn.linear_model import LogisticRegression

# Hyperparameter tuning
import optuna
from optuna.samplers import TPESampler

# Interpretability
import shap

# =============================================================================
# CONFIGURATION
# =============================================================================
RANDOM_STATE = 42
TARGET_COL = 'TenYearCHD'

# =============================================================================
# 1. DATA LOADING AND PREPARATION
# =============================================================================

def load_presplit_data(train_filepath=train_filepath,
                       test_filepath=test_filepath,
                       target_col_name='TenYearCHD'):
    """
    Load pre-split train and test datasets
    """
    print("="*80)
    print("STEP 1: LOADING PRE-SPLIT DATA")
    print("="*80)
    
    # Load training data
    print(f"\n✓ Loading training data from: {train_filepath}")
    train_df = pd.read_csv(train_filepath)
    print(f"  Shape: {train_df.shape}")
    
    # Load test data
    print(f"\n✓ Loading test data from: {test_filepath}")
    test_df = pd.read_csv(test_filepath)
    print(f"  Shape: {test_df.shape}")
    
    # Find target column
    if target_col_name not in train_df.columns:
        possible_targets = ['TenYearCHD', 'target', 'ten_year_chd']
        target_found = False
        for col in possible_targets:
            if col in train_df.columns:
                target_col_name = col
                target_found = True
                print(f"\n✓ Target column found: {target_col_name}")
                break
        
        if not target_found:
            raise ValueError(f"Target column '{target_col_name}' not found. Available columns: {train_df.columns.tolist()}")
    else:
        print(f"\n✓ Target column: {target_col_name}")
    
    # Separate features and target
    X_train = train_df.drop(columns=[target_col_name])
    y_train = train_df[target_col_name]
    
    X_test = test_df.drop(columns=[target_col_name])
    y_test = test_df[target_col_name]
    
    print(f"\n✓ Data split information:")
    print(f"  Training set: {X_train.shape}")
    print(f"  Test set: {X_test.shape}")
    
    # Verify feature consistency
    if list(X_train.columns) != list(X_test.columns):
        raise ValueError("Training and test sets have different features!")
    
    print(f"\n✓ Feature consistency verified")
    
    # Class distribution
    train_dist = y_train.value_counts().sort_index()
    print(f"\n✓ Training Set Class Distribution:")
    print(f"  Class 0 (No CHD): {train_dist[0]} ({train_dist[0]/len(y_train)*100:.2f}%)")
    print(f"  Class 1 (CHD): {train_dist[1]} ({train_dist[1]/len(y_train)*100:.2f}%)")
    print(f"  Imbalance Ratio: {train_dist[0]/train_dist[1]:.2f}:1")
    
    test_dist = y_test.value_counts().sort_index()
    print(f"\n✓ Test Set Class Distribution:")
    print(f"  Class 0 (No CHD): {test_dist[0]} ({test_dist[0]/len(y_test)*100:.2f}%)")
    print(f"  Class 1 (CHD): {test_dist[1]} ({test_dist[1]/len(y_test)*100:.2f}%)")
    print(f"  Imbalance Ratio: {test_dist[0]/test_dist[1]:.2f}:1")
    
    # Handle missing values
    train_missing = X_train.isnull().sum()
    test_missing = X_test.isnull().sum()
    
    if train_missing.any() or test_missing.any():
        print(f"\n⚠ Warning: Missing values detected")
        for col in X_train.columns:
            if X_train[col].dtype in ['float64', 'int64']:
                median_val = X_train[col].median()
                X_train[col].fillna(median_val, inplace=True)
                X_test[col].fillna(median_val, inplace=True)
            else:
                mode_val = X_train[col].mode()[0] if len(X_train[col].mode()) > 0 else X_train[col].iloc[0]
                X_train[col].fillna(mode_val, inplace=True)
                X_test[col].fillna(mode_val, inplace=True)
    
    # Handle categorical variables
    categorical_cols = X_train.select_dtypes(include=['object', 'category']).columns.tolist()
    
    if categorical_cols:
        print(f"\n✓ Encoding categorical variables: {categorical_cols}")
        label_encoders = {}
        for col in categorical_cols:
            le = LabelEncoder()
            X_train[col] = le.fit_transform(X_train[col].astype(str))
            X_test[col] = le.transform(X_test[col].astype(str))
            label_encoders[col] = le
    else:
        label_encoders = None
        print(f"\n✓ No categorical variables found (all numeric)")
    
    feature_names = X_train.columns.tolist()
    print(f"\n✓ Features ({len(feature_names)}):")
    for i, feat in enumerate(feature_names, 1):
        print(f"  {i:2d}. {feat}")
    
    return X_train, X_test, y_train, y_test, feature_names, label_encoders


# =============================================================================
# 2. HYPERPARAMETER TUNING WITH OPTUNA
# =============================================================================

def tune_xgboost(X_train, y_train, n_trials=50):
    """
    Optimize XGBoost hyperparameters using Optuna
    """
    print("\n" + "="*80)
    print("HYPERPARAMETER TUNING - XGBoost")
    print("="*80)
    
    # Calculate scale_pos_weight
    scale_pos_weight = (y_train == 0).sum() / (y_train == 1).sum()
    print(f"\n✓ Calculated scale_pos_weight: {scale_pos_weight:.2f}")
    
    def objective(trial):
        params = {
            'n_estimators': trial.suggest_int('n_estimators', 200, 600),
            'max_depth': trial.suggest_int('max_depth', 3, 6),
            'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.1),
            'subsample': trial.suggest_float('subsample', 0.7, 0.9),
            'colsample_bytree': trial.suggest_float('colsample_bytree', 0.7, 0.9),
            'scale_pos_weight': scale_pos_weight,
            'eval_metric': 'auc',
            'random_state': RANDOM_STATE,
            'use_label_encoder': False
        }
        
        model = XGBClassifier(**params)
        cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)
        
        scores = []
        for train_idx, val_idx in cv.split(X_train, y_train):
            X_tr, X_val = X_train.iloc[train_idx], X_train.iloc[val_idx]
            y_tr, y_val = y_train.iloc[train_idx], y_train.iloc[val_idx]
            
            model.fit(X_tr, y_tr)
            y_pred_proba = model.predict_proba(X_val)[:, 1]
            score = roc_auc_score(y_val, y_pred_proba)
            scores.append(score)
        
        return np.mean(scores)
    
    print(f"\n✓ Starting Optuna optimization ({n_trials} trials)...")
    print("  Objective: Maximize ROC-AUC")
    
    study = optuna.create_study(direction='maximize', sampler=TPESampler(seed=RANDOM_STATE))
    study.optimize(objective, n_trials=n_trials, show_progress_bar=True)
    
    print(f"\n✓ Optimization completed!")
    print(f"  Best ROC-AUC: {study.best_value:.4f}")
    print(f"  Best parameters:")
    for key, value in study.best_params.items():
        print(f"    {key}: {value}")
    
    best_params = study.best_params.copy()
    best_params['scale_pos_weight'] = scale_pos_weight
    best_params['eval_metric'] = 'auc'
    best_params['random_state'] = RANDOM_STATE
    best_params['use_label_encoder'] = False
    
    return best_params


def tune_lightgbm(X_train, y_train, n_trials=50):
    """
    Optimize LightGBM hyperparameters using Optuna
    """
    print("\n" + "="*80)
    print("HYPERPARAMETER TUNING - LightGBM")
    print("="*80)
    
    # Calculate scale_pos_weight
    scale_pos_weight = (y_train == 0).sum() / (y_train == 1).sum()
    print(f"\n✓ Calculated scale_pos_weight: {scale_pos_weight:.2f}")
    
    def objective(trial):
        params = {
            'n_estimators': trial.suggest_int('n_estimators', 200, 600),
            'num_leaves': trial.suggest_int('num_leaves', 20, 50),
            'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.1),
            'subsample': trial.suggest_float('subsample', 0.7, 0.9),
            'colsample_bytree': trial.suggest_float('colsample_bytree', 0.7, 0.9),
            'scale_pos_weight': scale_pos_weight,
            'random_state': RANDOM_STATE,
            'verbose': -1
        }
        
        model = LGBMClassifier(**params)
        cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)
        
        scores = []
        for train_idx, val_idx in cv.split(X_train, y_train):
            X_tr, X_val = X_train.iloc[train_idx], X_train.iloc[val_idx]
            y_tr, y_val = y_train.iloc[train_idx], y_train.iloc[val_idx]
            
            model.fit(X_tr, y_tr)
            y_pred_proba = model.predict_proba(X_val)[:, 1]
            score = roc_auc_score(y_val, y_pred_proba)
            scores.append(score)
        
        return np.mean(scores)
    
    print(f"\n✓ Starting Optuna optimization ({n_trials} trials)...")
    print("  Objective: Maximize ROC-AUC")
    
    study = optuna.create_study(direction='maximize', sampler=TPESampler(seed=RANDOM_STATE))
    study.optimize(objective, n_trials=n_trials, show_progress_bar=True)
    
    print(f"\n✓ Optimization completed!")
    print(f"  Best ROC-AUC: {study.best_value:.4f}")
    print(f"  Best parameters:")
    for key, value in study.best_params.items():
        print(f"    {key}: {value}")
    
    best_params = study.best_params.copy()
    best_params['scale_pos_weight'] = scale_pos_weight
    best_params['random_state'] = RANDOM_STATE
    best_params['verbose'] = -1
    
    return best_params


def tune_adaboost(X_train, y_train, n_trials=40):
    """
    Optimize AdaBoost hyperparameters using Optuna
    Uses sample_weight to handle imbalance
    """
    print("\n" + "="*80)
    print("HYPERPARAMETER TUNING - AdaBoost")
    print("="*80)

    # Calculate sample weights for imbalance
    class_counts = y_train.value_counts()
    class_weight = len(y_train) / (2 * class_counts)
    sample_weights = y_train.map(class_weight)
    
    print(f"\n✓ Using sample_weight to handle imbalance")
    print(f"  Class 0 weight: {class_weight[0]:.3f}")
    print(f"  Class 1 weight: {class_weight[1]:.3f}")
    
    def objective(trial):
        params = {
            'n_estimators': trial.suggest_int('n_estimators', 50, 400),
            'learning_rate': trial.suggest_float('learning_rate', 0.01, 1.0),
            'algorithm': 'SAMME',  # Better for probability estimates
            'random_state': RANDOM_STATE,
        }
        
        model = AdaBoostClassifier(**params)
        cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)
        
        scores = []
        for train_idx, val_idx in cv.split(X_train, y_train):
            X_tr, X_val = X_train.iloc[train_idx], X_train.iloc[val_idx]
            y_tr, y_val = y_train.iloc[train_idx], y_train.iloc[val_idx]
            sw_tr = sample_weights.iloc[train_idx]
            
            # Fit with sample weights
            model.fit(X_tr, y_tr, sample_weight=sw_tr)
            y_pred_proba = model.predict_proba(X_val)[:, 1]
            score = roc_auc_score(y_val, y_pred_proba)
            scores.append(score)
        
        return np.mean(scores)
    
    print(f"\n✓ Starting Optuna optimization ({n_trials} trials)...")
    print("  Objective: Maximize ROC-AUC")
    
    study = optuna.create_study(direction='maximize', sampler=TPESampler(seed=RANDOM_STATE))
    study.optimize(objective, n_trials=n_trials, show_progress_bar=True)
    
    print(f"\n✓ Optimization completed!")
    print(f"  Best ROC-AUC: {study.best_value:.4f}")
    print(f"  Best parameters:")
    for key, value in study.best_params.items():
        print(f"    {key}: {value}")
    
    best_params = study.best_params.copy()
    best_params['random_state'] = RANDOM_STATE
    
    return best_params


# =============================================================================
# 3. MODEL TRAINING AND EVALUATION
# =============================================================================

def train_base_models(X_train, y_train, X_test, y_test, 
                     best_xgb_params, best_lgbm_params, best_ada_params):
    """
    Train base ensemble models with optimized hyperparameters
    """
    print("\n" + "="*80)
    print("TRAINING BASE ENSEMBLE MODELS")
    print("="*80)
    
    models = {
        'XGBoost': XGBClassifier(**best_xgb_params),
        'LightGBM': LGBMClassifier(**best_lgbm_params),
        'AdaBoost': AdaBoostClassifier(**best_ada_params)
    }
    
    results = {}
    trained_models = {}
    
    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)
    scoring = {
        'accuracy': 'accuracy',
        'precision': 'precision',
        'recall': 'recall',
        'f1': 'f1',
        'roc_auc': 'roc_auc'
    }
    
    for name, model in models.items():
        print(f"\n{'='*80}")
        print(f"Training: {name}")
        print(f"{'='*80}")
        
        # Cross-validation
        print(f"  Running 5-fold cross-validation...")

        if name == 'AdaBoost':
            # For AdaBoost, we custom CV with sample_weight
            cv_scores = {'test_roc_auc': [], 'test_recall': [], 'test_precision': [], 
                        'test_f1': [], 'test_accuracy': []}
            
            cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)

                # Calculate sample weights for imbalance
            class_counts = y_train.value_counts()
            class_weight = len(y_train) / (2 * class_counts)
            sample_weights = y_train.map(class_weight)
            for train_idx, val_idx in cv.split(X_train, y_train):
                X_tr, X_val = X_train.iloc[train_idx], X_train.iloc[val_idx]
                y_tr, y_val = y_train.iloc[train_idx], y_train.iloc[val_idx]
                sw_tr = sample_weights.iloc[train_idx]
                
                model.fit(X_tr, y_tr, sample_weight=sw_tr)
                y_pred = model.predict(X_val)
                y_proba = model.predict_proba(X_val)[:, 1]
                
                cv_scores['test_roc_auc'].append(roc_auc_score(y_val, y_proba))
                cv_scores['test_recall'].append(recall_score(y_val, y_pred))
                cv_scores['test_precision'].append(precision_score(y_val, y_pred, zero_division=0))
                cv_scores['test_f1'].append(f1_score(y_val, y_pred))
                cv_scores['test_accuracy'].append(accuracy_score(y_val, y_pred))
            
            cv_results = {k: np.array(v) for k, v in cv_scores.items()}
            
            # Train final model with sample weights
            model.fit(X_train, y_train, sample_weight=sample_weights)
        else:
            cv_results = cross_validate(
                model, X_train, y_train,
                cv=cv, scoring=scoring, n_jobs=-1,
                return_train_score=True
            )
            model.fit(X_train, y_train)
        
        # Predictions
        y_train_pred = model.predict(X_train)
        y_test_pred = model.predict(X_test)
        y_test_proba = model.predict_proba(X_test)[:, 1]
        
        # Calculate metrics
        train_metrics = {
            'accuracy': accuracy_score(y_train, y_train_pred),
            'precision': precision_score(y_train, y_train_pred, zero_division=0),
            'recall': recall_score(y_train, y_train_pred),
            'f1': f1_score(y_train, y_train_pred),
            'roc_auc': roc_auc_score(y_train, model.predict_proba(X_train)[:, 1])
        }
        
        test_metrics = {
            'accuracy': accuracy_score(y_test, y_test_pred),
            'precision': precision_score(y_test, y_test_pred, zero_division=0),
            'recall': recall_score(y_test, y_test_pred),
            'f1': f1_score(y_test, y_test_pred),
            'roc_auc': roc_auc_score(y_test, y_test_proba)
        }
        
        cv_metrics = {
            'cv_accuracy_mean': cv_results['test_accuracy'].mean(),
            'cv_accuracy_std': cv_results['test_accuracy'].std(),
            'cv_precision_mean': cv_results['test_precision'].mean(),
            'cv_precision_std': cv_results['test_precision'].std(),
            'cv_recall_mean': cv_results['test_recall'].mean(),
            'cv_recall_std': cv_results['test_recall'].std(),
            'cv_f1_mean': cv_results['test_f1'].mean(),
            'cv_f1_std': cv_results['test_f1'].std(),
            'cv_roc_auc_mean': cv_results['test_roc_auc'].mean(),
            'cv_roc_auc_std': cv_results['test_roc_auc'].std(),
        }
        
        # Store results
        results[name] = {
            'train_metrics': train_metrics,
            'metrics': test_metrics,
            'cv_metrics': cv_metrics,
            'confusion_matrix': confusion_matrix(y_test, y_test_pred),
            'y_pred': y_test_pred,
            'y_proba': y_test_proba,
            'classification_report': classification_report(y_test, y_test_pred, output_dict=True)
        }
        
        trained_models[name] = model
        
        # Print results
        print(f"\n  Cross-Validation Results (mean ± std):")
        print(f"    Accuracy:  {cv_metrics['cv_accuracy_mean']:.4f} ± {cv_metrics['cv_accuracy_std']:.4f}")
        print(f"    Precision: {cv_metrics['cv_precision_mean']:.4f} ± {cv_metrics['cv_precision_std']:.4f}")
        print(f"    Recall:    {cv_metrics['cv_recall_mean']:.4f} ± {cv_metrics['cv_recall_std']:.4f}")
        print(f"    F1-Score:  {cv_metrics['cv_f1_mean']:.4f} ± {cv_metrics['cv_f1_std']:.4f}")
        print(f"    ROC-AUC:   {cv_metrics['cv_roc_auc_mean']:.4f} ± {cv_metrics['cv_roc_auc_std']:.4f}")
        
        print(f"\n  Test Set Performance:")
        print(f"    Accuracy:  {test_metrics['accuracy']:.4f}")
        print(f"    Precision: {test_metrics['precision']:.4f}")
        print(f"    Recall:    {test_metrics['recall']:.4f}")
        print(f"    F1-Score:  {test_metrics['f1']:.4f}")
        print(f"    ROC-AUC:   {test_metrics['roc_auc']:.4f}")
    
    return results, trained_models


def create_stacking_ensemble(base_models, X_train, y_train):
    """
    Create stacking ensemble with Logistic Regression meta-learner
    """
    print("\n" + "="*80)
    print("CREATING STACKING ENSEMBLE")
    print("="*80)
    
    estimators = [
        ('lr', LogisticRegression(
            max_iter=1000,
            class_weight='balanced',
            random_state=RANDOM_STATE)),
        ('xgb', base_models['XGBoost']),
        ('lgbm', base_models['LightGBM'])
    ]
    
    stacking_clf = StackingClassifier(
        estimators=estimators,
        final_estimator=LogisticRegression(
            max_iter=1000,
            class_weight='balanced',
            random_state=RANDOM_STATE),
        cv=5,
        n_jobs=-1
    )
    
    print("\n✓ Training stacking ensemble...")
    print(f"  Base estimators: {len(estimators)}")
    print(f"  Meta-learner: Logistic Regression")
    
    stacking_clf.fit(X_train, y_train)
    
    print("✓ Stacking ensemble trained successfully!")
    
    return stacking_clf


def evaluate_model(model, X_test, y_test, model_name):
    """
    Comprehensive model evaluation
    """
    y_pred = model.predict(X_test)
    y_proba = model.predict_proba(X_test)[:, 1]
    
    metrics = {
        'accuracy': accuracy_score(y_test, y_pred),
        'precision': precision_score(y_test, y_pred, zero_division=0),
        'recall': recall_score(y_test, y_pred),
        'f1': f1_score(y_test, y_pred),
        'roc_auc': roc_auc_score(y_test, y_proba)
    }
    
    cm = confusion_matrix(y_test, y_pred)
    report = classification_report(y_test, y_pred, output_dict=True)
    
    return {
        'metrics': metrics,
        'confusion_matrix': cm,
        'classification_report': report,
        'y_pred': y_pred,
        'y_proba': y_proba
    }


# =============================================================================
# 4. THRESHOLD OPTIMIZATION
# =============================================================================

def optimize_threshold_for_recall(model, X, y):
    """
    Optimize classification threshold to maximize recall
    """
    probs = model.predict_proba(X)[:, 1]
    precision, recall, thresholds = precision_recall_curve(y, probs)
    
    # Find threshold that maximizes recall
    idx = np.argmax(recall)
    optimal_threshold = thresholds[idx] if idx < len(thresholds) else 0.5
    optimal_recall = recall[idx]
    
    return optimal_threshold, optimal_recall


# =============================================================================
# 5. VISUALIZATION
# =============================================================================

def plot_roc_curves(results_dict, y_test, save_path='roc_curves_comparison.png'):
    """
    Plot ROC curves for all models
    """
    plt.figure(figsize=(10, 8))
    
    for name, results in results_dict.items():
        fpr, tpr, _ = roc_curve(y_test, results['y_proba'])
        auc = results['metrics']['roc_auc']
        plt.plot(fpr, tpr, label=f"{name} (AUC = {auc:.4f})", linewidth=2)
    
    plt.plot([0, 1], [0, 1], 'k--', label='Random (AUC = 0.5000)')
    plt.xlabel('False Positive Rate', fontsize=12)
    plt.ylabel('True Positive Rate', fontsize=12)
    plt.title('ROC Curves - Model Comparison', fontsize=14, fontweight='bold')
    plt.legend(loc='lower right', fontsize=10)
    plt.grid(alpha=0.3)
    plt.tight_layout()
    plt.savefig(save_path, dpi=300, bbox_inches='tight')
    print(f"\n✓ ROC curves saved: {save_path}")
    plt.close()


def plot_confusion_matrices(results_dict, save_path='confusion_matrices.png'):
    """
    Plot confusion matrices for all models
    """
    n_models = len(results_dict)
    fig, axes = plt.subplots(1, n_models, figsize=(5*n_models, 4))
    
    if n_models == 1:
        axes = [axes]
    
    for idx, (name, results) in enumerate(results_dict.items()):
        cm = results['confusion_matrix']
        sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', 
                   xticklabels=['No CHD', 'CHD'],
                   yticklabels=['No CHD', 'CHD'],
                   ax=axes[idx])
        axes[idx].set_title(f'{name}', fontweight='bold')
        axes[idx].set_ylabel('True Label')
        axes[idx].set_xlabel('Predicted Label')
    
    plt.tight_layout()
    plt.savefig(save_path, dpi=300, bbox_inches='tight')
    print(f"✓ Confusion matrices saved: {save_path}")
    plt.close()


# =============================================================================
# 6. FEATURE IMPORTANCE AND INTERPRETABILITY
# =============================================================================

def analyze_feature_importance(model, feature_names, model_name='Model'):
    """
    Analyze and plot feature importance
    """
    print(f"\n{'='*80}")
    print(f"Feature Importance Analysis - {model_name}")
    print(f"{'='*80}")
    
    if not hasattr(model, 'feature_importances_'):
        print(f"  {model_name} does not have feature_importances_ attribute")
        return None
    
    importance = model.feature_importances_
    
    importance_df = pd.DataFrame({
        'feature': feature_names,
        'importance': importance
    }).sort_values('importance', ascending=False)
    
    print(f"\nTop 10 Most Important Features:")
    for idx, row in importance_df.head(10).iterrows():
        print(f"  {row['feature']:25s}: {row['importance']:.4f}")
    
    # Plot
    plt.figure(figsize=(10, 8))
    top_n = min(15, len(importance_df))
    plt.barh(range(top_n), importance_df['importance'].head(top_n))
    plt.yticks(range(top_n), importance_df['feature'].head(top_n))
    plt.xlabel('Importance', fontsize=12)
    plt.title(f'Feature Importance - {model_name}', fontsize=14, fontweight='bold')
    plt.gca().invert_yaxis()
    plt.tight_layout()
    filename = f'feature_importance_{model_name.lower().replace(" ", "_")}.png'
    plt.savefig(filename, dpi=300, bbox_inches='tight')
    print(f"\n✓ Feature importance plot saved: {filename}")
    plt.close()
    
    return importance_df


def shap_analysis(model, X_test, feature_names, model_name='Model', max_display=15):
    """
    SHAP analysis for model interpretability
    """
    print(f"\n{'='*80}")
    print(f"SHAP Analysis - {model_name}")
    print(f"{'='*80}")
    
    try:
        print("\n✓ Creating SHAP explainer...")
        explainer = shap.TreeExplainer(model)
        
        sample_size = min(500, len(X_test))
        X_sample = X_test.sample(n=sample_size, random_state=RANDOM_STATE)
        
        print(f"✓ Calculating SHAP values for {sample_size} samples...")
        shap_values = explainer.shap_values(X_sample)
        
        if isinstance(shap_values, list):
            shap_values = shap_values[1]
        
        # Summary plot
        plt.figure(figsize=(10, 8))
        shap.summary_plot(shap_values, X_sample, feature_names=feature_names,
                         max_display=max_display, show=False)
        plt.tight_layout()
        filename = f'shap_summary_{model_name.lower().replace(" ", "_")}.png'
        plt.savefig(filename, dpi=300, bbox_inches='tight')
        print(f"✓ SHAP summary plot saved: {filename}")
        plt.close()
        
        shap_importance = np.abs(shap_values).mean(axis=0)
        shap_df = pd.DataFrame({
            'feature': feature_names,
            'shap_importance': shap_importance
        }).sort_values('shap_importance', ascending=False)
        
        print(f"\nTop 10 Features by SHAP Importance:")
        for idx, row in shap_df.head(10).iterrows():
            print(f"  {row['feature']:25s}: {row['shap_importance']:.4f}")
        
        return shap_df
        
    except Exception as e:
        print(f"✗ SHAP analysis failed: {str(e)}")
        return None


# =============================================================================
# 7. LEARNING AND VALIDATION CURVES
# =============================================================================

def plot_learning_curves(model, X_train, y_train, model_name='Model'):
    """
    Plot learning curves
    """
    print(f"\n{'='*80}")
    print(f"Learning Curves - {model_name}")
    print(f"{'='*80}")
    
    train_sizes, train_scores, val_scores = learning_curve(
        model, X_train, y_train,
        train_sizes=np.linspace(0.1, 1.0, 5),
        cv=5,
        scoring='roc_auc',
        n_jobs=-1,
        random_state=RANDOM_STATE
    )
    
    train_mean = train_scores.mean(axis=1)
    train_std = train_scores.std(axis=1)
    val_mean = val_scores.mean(axis=1)
    val_std = val_scores.std(axis=1)
    
    plt.figure(figsize=(10, 6))
    plt.plot(train_sizes, train_mean, 'o-', color='blue', label='Training score')
    plt.fill_between(train_sizes, train_mean - train_std, train_mean + train_std, 
                     alpha=0.1, color='blue')
    plt.plot(train_sizes, val_mean, 'o-', color='red', label='Cross-validation score')
    plt.fill_between(train_sizes, val_mean - val_std, val_mean + val_std, 
                     alpha=0.1, color='red')
    
    plt.xlabel('Training Set Size', fontsize=12)
    plt.ylabel('ROC-AUC Score', fontsize=12)
    plt.title(f'Learning Curves - {model_name}', fontsize=14, fontweight='bold')
    plt.legend(loc='best', fontsize=10)
    plt.grid(alpha=0.3)
    plt.tight_layout()
    
    filename = f'learning_curves_{model_name.lower().replace(" ", "_")}.png'
    plt.savefig(filename, dpi=300, bbox_inches='tight')
    print(f"✓ Learning curves saved: {filename}")
    plt.close()
    
    return {
        'train_sizes': train_sizes.tolist(),
        'train_auc': train_mean.tolist(),
        'val_auc': val_mean.tolist()
    }


def plot_validation_curve(model, X_train, y_train, model_name='Model'):
    """
    Plot validation curve for n_estimators
    """
    print(f"\n{'='*80}")
    print(f"Validation Curve - {model_name}")
    print(f"{'='*80}")
    
    if not hasattr(model, 'n_estimators'):
        print(f"  Model does not have n_estimators parameter")
        return None
    
    param_range = [50, 100, 200, 400]
    
    train_scores, val_scores = validation_curve(
        model, X_train, y_train,
        param_name='n_estimators',
        param_range=param_range,
        cv=5,
        scoring='roc_auc',
        n_jobs=-1
    )
    
    train_mean = train_scores.mean(axis=1)
    train_std = train_scores.std(axis=1)
    val_mean = val_scores.mean(axis=1)
    val_std = val_scores.std(axis=1)
    
    plt.figure(figsize=(10, 6))
    plt.plot(param_range, train_mean, 'o-', color='blue', label='Training score')
    plt.fill_between(param_range, train_mean - train_std, train_mean + train_std, 
                     alpha=0.1, color='blue')
    plt.plot(param_range, val_mean, 'o-', color='red', label='Cross-validation score')
    plt.fill_between(param_range, val_mean - val_std, val_mean + val_std, 
                     alpha=0.1, color='red')
    
    plt.xlabel('n_estimators', fontsize=12)
    plt.ylabel('ROC-AUC Score', fontsize=12)
    plt.title(f'Validation Curve - {model_name} - n_estimators', 
              fontsize=14, fontweight='bold')
    plt.legend(loc='best', fontsize=10)
    plt.grid(alpha=0.3)
    plt.tight_layout()
    
    filename = f'validation_curve_{model_name.lower().replace(" ", "_")}.png'
    plt.savefig(filename, dpi=300, bbox_inches='tight')
    print(f"✓ Validation curve saved: {filename}")
    plt.close()
    
    return {
        'param_name': 'n_estimators',
        'param_range': param_range,
        'train_auc': train_mean.tolist(),
        'val_auc': val_mean.tolist()
    }


# =============================================================================
# 8. MODEL SELECTION
# =============================================================================

def select_best_model(results_dict, models_dict, X_test, y_test):
    """
    Select best model based on weighted score
    Weight: 0.7 * ROC-AUC + 0.3 * Recall
    """
    print("\n" + "="*80)
    print("MODEL SELECTION")
    print("="*80)
    
    final_scores = {}
    for name, model in models_dict.items():
        y_proba = model.predict_proba(X_test)[:, 1]
        y_pred = model.predict(X_test)
        
        roc_auc = roc_auc_score(y_test, y_proba)
        recall = recall_score(y_test, y_pred)
        
        final_scores[name] = 0.7 * roc_auc + 0.3 * recall
    
    best_model_name = max(final_scores, key=final_scores.get)
    best_model = models_dict[best_model_name]
    
    print("\n✓ Final Weighted Scores (0.7*ROC_AUC + 0.3*Recall):")
    for name, score in sorted(final_scores.items(), key=lambda x: x[1], reverse=True):
        print(f"  {name:15s}: {score:.4f}")
    
    print("\n" + "="*80)
    print(f"🏆 BEST MODEL: {best_model_name}")
    print(f"   Weighted Score: {final_scores[best_model_name]:.4f}")
    print("="*80)
    
    return best_model_name, best_model, final_scores


# =============================================================================
# 9. SAVE MODEL AND METADATA
# =============================================================================

def save_final_model(model, model_name, feature_names, metrics, 
                     hyperparameters, final_scores, optimal_threshold,
                     optimal_recall, learning_curve_data, validation_curve_data,
                     label_encoders=None, save_dir='models'):
    """
    Save the final selected model with complete metadata
    """
    print("\n" + "="*80)
    print("SAVING FINAL MODEL")
    print("="*80)
    
    import os
    os.makedirs(save_dir, exist_ok=True)
    
    # Save model
    model_path = os.path.join(save_dir, 'best_model.pkl')
    with open(model_path, 'wb') as f:
        pickle.dump(model, f)
    print(f"\n✓ Model saved: {model_path}")
    
    # Save metadata
    metadata = {
        'model_name': model_name,
        'model_type': type(model).__name__,
        'training_date': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
        'feature_names': feature_names,
        'n_features': len(feature_names),
        'test_metrics': metrics,
        'tuned_hyperparameters': hyperparameters,
        'final_scores': final_scores,
        'optimal_threshold': float(optimal_threshold),
        'optimal_recall': float(optimal_recall),
        'learning_curve': learning_curve_data,
        'validation_curve': validation_curve_data,
        'imbalance_handling': 'scale_pos_weight',
        'hyperparameter_tuning': 'Optuna (50 trials for boosting, 40 for AdaBoost)',
        'label_encoders': {k: v.classes_.tolist() for k, v in label_encoders.items()} 
                          if label_encoders else None,
    }
    
    metadata_path = os.path.join(save_dir, 'model_metadata.json')
    with open(metadata_path, 'w') as f:
        json.dump(metadata, f, indent=4)
    print(f"✓ Metadata saved: {metadata_path}")
    
    if label_encoders:
        encoders_path = os.path.join(save_dir, 'label_encoders.pkl')
        with open(encoders_path, 'wb') as f:
            pickle.dump(label_encoders, f)
        print(f"✓ Label encoders saved: {encoders_path}")
    
    print(f"\n✓ All artifacts saved to: {save_dir}/")
    
    return model_path, metadata_path


def create_model_comparison_csv(results_dict, output_file='model_comparison_boosting.csv'):
    """
    Create CSV file comparing all models
    """
    print("\n" + "="*80)
    print("CREATING MODEL COMPARISON TABLE")
    print("="*80)
    
    comparison_data = []
    
    for name, results in results_dict.items():
        metrics = results['metrics']
        row = {
            'Model': name,
            'Accuracy': metrics['accuracy'],
            'Precision': metrics['precision'],
            'Recall': metrics['recall'],
            'F1-Score': metrics['f1'],
            'ROC-AUC': metrics['roc_auc']
        }
        comparison_data.append(row)
    
    df = pd.DataFrame(comparison_data)
    df = df.sort_values('ROC-AUC', ascending=False)
    df.to_csv(output_file, index=False)
    
    print(f"\n✓ Model comparison saved: {output_file}")
    print("\nModel Comparison Table:")
    print(df.to_string(index=False))
    
    return df


# =============================================================================
# 10. MAIN EXECUTION PIPELINE
# =============================================================================

def main(train_filepath=None,
         test_filepath=None,
         target_col_name='TenYearCHD'):
    """
    Main execution pipeline for Collaborator 5
    """
    print("\n" + "="*80)
    print("CORONARY HEART DISEASE PREDICTION PROJECT")
    print("Advanced Models & Model Selection - Collaborator 5")
    print("="*80)
    print(f"Start Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("="*80)
    
    # =========================================================================
    # STEP 1: Load data
    # =========================================================================
    assert train_filepath and test_filepath, "Please provide train and test file paths"
    X_train, X_test, y_train, y_test, feature_names, label_encoders = load_presplit_data(
        train_filepath=train_filepath,
        test_filepath=test_filepath,
        target_col_name=target_col_name
    )
    
    # =========================================================================
    # STEP 2: Hyperparameter tuning with Optuna
    # =========================================================================
    best_xgb_params = tune_xgboost(X_train, y_train, n_trials=50)
    best_lgbm_params = tune_lightgbm(X_train, y_train, n_trials=50)
    best_ada_params = tune_adaboost(X_train, y_train, n_trials=40)
    
    all_hyperparameters = {
        'xgboost': best_xgb_params,
        'lightgbm': best_lgbm_params,
        'adaboost': best_ada_params
    }
    
    # =========================================================================
    # STEP 3: Train base models
    # =========================================================================
    base_results, base_models = train_base_models(
        X_train, y_train, X_test, y_test,
        best_xgb_params, best_lgbm_params, best_ada_params
    )
    
    # =========================================================================
    # STEP 4: Create stacking ensemble
    # =========================================================================
    stacking_model = create_stacking_ensemble(base_models, X_train, y_train)
    
    # =========================================================================
    # STEP 5: Evaluate all models
    # =========================================================================
    all_models = {
        'XGBoost': base_models['XGBoost'],
        'LightGBM': base_models['LightGBM'],
        'AdaBoost': base_models['AdaBoost'],
        'Stacking': stacking_model
    }
    
    all_results = base_results.copy()
    all_results['Stacking'] = evaluate_model(stacking_model, X_test, y_test, 'Stacking')
    
    # Add CV metrics for stacking
    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)
    cv_results = cross_validate(
        stacking_model, X_train, y_train,
        cv=cv, scoring={'roc_auc': 'roc_auc', 'recall': 'recall'}, n_jobs=-1
    )
    all_results['Stacking']['cv_roc_auc_mean'] = cv_results['test_roc_auc'].mean()
    all_results['Stacking']['cv_recall_mean'] = cv_results['test_recall'].mean()
    
    # =========================================================================
    # STEP 6: Visualizations
    # =========================================================================
    print("\n" + "="*80)
    print("GENERATING VISUALIZATIONS")
    print("="*80)
    
    plot_roc_curves(all_results, y_test)
    plot_confusion_matrices(all_results)
    
    # =========================================================================
    # STEP 7: Feature importance and SHAP
    # =========================================================================
    print("\n" + "="*80)
    print("FEATURE IMPORTANCE & INTERPRETABILITY")
    print("="*80)
    
    xgb_importance = analyze_feature_importance(
        base_models['XGBoost'], feature_names, 'XGBoost'
    )
    
    shap_importance = shap_analysis(
        base_models['XGBoost'], X_test, feature_names, 'XGBoost'
    )
    
    lgbm_importance = analyze_feature_importance(
        base_models['LightGBM'], feature_names, 'LightGBM'
    )

    shap_importance = shap_analysis(
        base_models['LightGBM'], X_test, feature_names, 'LightGBM'
    )
    
    ada_importance = analyze_feature_importance(
        base_models['AdaBoost'], feature_names, 'AdaBoost'
    )

    shap_importance = shap_analysis(
        base_models['AdaBoost'], X_test, feature_names, 'AdaBoost'
    )
    
    # =========================================================================
    # STEP 8: Learning and validation curves
    # =========================================================================
    print("\n" + "="*80)
    print("LEARNING AND VALIDATION CURVES")
    print("="*80)
    
    learning_curve_xgb = plot_learning_curves(
        base_models['XGBoost'], X_train, y_train, 'XGBoost'
    )
    
    validation_curve_xgb = plot_validation_curve(
        base_models['XGBoost'], X_train, y_train, 'XGBoost'
    )

    learning_curve_lgbm = plot_learning_curves(
        base_models['LightGBM'], X_train, y_train, 'LightGBM'
    )
    
    validation_curve_lgbm = plot_validation_curve(
        base_models['LightGBM'], X_train, y_train, 'LightGBM'
    )

    learning_curve_ada = plot_learning_curves(
        base_models['AdaBoost'], X_train, y_train, 'AdaBoost'
    )
    
    validation_curve_ada = plot_validation_curve(
        base_models['AdaBoost'], X_train, y_train, 'AdaBoost'
    )
    
    # =========================================================================
    # STEP 9: Create comparison table
    # =========================================================================
    comparison_df = create_model_comparison_csv(all_results)
    return comparison_df

In [ ]:
# =============================================================================
# RUN THE PIPELINE
# =============================================================================

if __name__ == "__main__":
    """
    Run the Advanced Models pipeline
    
    Usage:
    ------
    python advanced_models.py
    
    Or with custom paths:
    results = main(
        train_filepath='processed/train_unscaled.csv',
        test_filepath='processed/test_unscaled.csv'
    )
    """
    
    results = main(
        train_filepath=train_filepath,
        test_filepath=test_filepath,
        target_col_name='TenYearCHD'
    )

In [15]:
data = ["unscaled", "standard_scaled", "robust_scaled"]

for i in data:
    train_filepath = os.path.join(DATA_DIR, f'train_{i}.csv')
    test_filepath = os.path.join(DATA_DIR, f'test_{i}.csv')
    results = main(
        train_filepath=train_filepath,
        test_filepath=test_filepath,
        target_col_name='TenYearCHD'
    )

[I 2026-01-11 00:06:19,883] A new study created in memory with name: no-name-774ca7b2-97a7-4d68-ae90-82b95a6fafda

================================================================================
CORONARY HEART DISEASE PREDICTION PROJECT
Advanced Models & Model Selection - Collaborator 5
================================================================================
Start Time: 2026-01-11 00:06:19
================================================================================
================================================================================
STEP 1: LOADING PRE-SPLIT DATA
================================================================================

✓ Loading training data from: ../data/processed\train_unscaled.csv
  Shape: (3390, 9)

✓ Loading test data from: ../data/processed\test_unscaled.csv
  Shape: (848, 9)

✓ Target column: TenYearCHD

✓ Data split information:
  Training set: (3390, 8)
  Test set: (848, 8)

✓ Feature consistency verified

✓ Training Set Class Distribution:
  Class 0 (No CHD): 2875 (84.81%)
  Class 1 (CHD): 515 (15.19%)
  Imbalance Ratio: 5.58:1

✓ Test Set Class Distribution:
  Class 0 (No CHD): 719 (84.79%)
  Class 1 (CHD): 129 (15.21%)
  Imbalance Ratio: 5.57:1

✓ No categorical variables found (all numeric)

✓ Features (8):
   1. bmi
   2. hypertension
   3. pulse_pressure
   4. cigarettes_per_day
   5. total_cholesterol
   6. glucose
   7. heart_rate
   8. age_group_code

================================================================================
HYPERPARAMETER TUNING - XGBoost
================================================================================

✓ Calculated scale_pos_weight: 5.58

✓ Starting Optuna optimization (50 trials)...
  Objective: Maximize ROC-AUC

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-01-11 00:06:20,584] Trial 0 finished with value: 0.6456395103419164 and parameters: {'n_estimators': 350, 'max_depth': 6, 'learning_rate': 0.07587945476302646, 'subsample': 0.8197316968394073, 'colsample_bytree': 0.7312037280884873}. Best is trial 0 with value: 0.6456395103419164.
[I 2026-01-11 00:06:20,877] Trial 1 finished with value: 0.6734250738708316 and parameters: {'n_estimators': 262, 'max_depth': 3, 'learning_rate': 0.08795585311974417, 'subsample': 0.8202230023486418, 'colsample_bytree': 0.8416145155592091}. Best is trial 1 with value: 0.6734250738708316.
[I 2026-01-11 00:06:21,291] Trial 2 finished with value: 0.657668214436471 and parameters: {'n_estimators': 208, 'max_depth': 6, 'learning_rate': 0.08491983767203796, 'subsample': 0.7424678221356552, 'colsample_bytree': 0.73636499344142}. Best is trial 1 with value: 0.6734250738708316.
[I 2026-01-11 00:06:21,659] Trial 3 finished with value: 0.6770417897847193 and parameters: {'n_estimators': 273, 'max_depth': 4, 'learning_rate': 0.05722807884690141, 'subsample': 0.7863890037284231, 'colsample_bytree': 0.7582458280396084}. Best is trial 3 with value: 0.6770417897847193.
[I 2026-01-11 00:06:22,137] Trial 4 finished with value: 0.6836403545799915 and parameters: {'n_estimators': 445, 'max_depth': 3, 'learning_rate': 0.03629301836816964, 'subsample': 0.7732723686587383, 'colsample_bytree': 0.7912139968434072}. Best is trial 4 with value: 0.6836403545799915.
[I 2026-01-11 00:06:22,663] Trial 5 finished with value: 0.6694504010130856 and parameters: {'n_estimators': 514, 'max_depth': 3, 'learning_rate': 0.05628109945722505, 'subsample': 0.8184829137724084, 'colsample_bytree': 0.7092900825439995}. Best is trial 4 with value: 0.6836403545799915.
[I 2026-01-11 00:06:23,117] Trial 6 finished with value: 0.6994681300126636 and parameters: {'n_estimators': 443, 'max_depth': 3, 'learning_rate': 0.015854643368675158, 'subsample': 0.8897771074506666, 'colsample_bytree': 0.8931264066149118}. Best is trial 6 with value: 0.6994681300126636.
[I 2026-01-11 00:06:23,763] Trial 7 finished with value: 0.688216124947235 and parameters: {'n_estimators': 524, 'max_depth': 4, 'learning_rate': 0.018790490260574548, 'subsample': 0.8368466053024314, 'colsample_bytree': 0.7880304987479203}. Best is trial 6 with value: 0.6994681300126636.
[I 2026-01-11 00:06:24,136] Trial 8 finished with value: 0.7059113550021106 and parameters: {'n_estimators': 248, 'max_depth': 4, 'learning_rate': 0.013094966900369657, 'subsample': 0.8818640804157565, 'colsample_bytree': 0.7517559963200033}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:06:24,733] Trial 9 finished with value: 0.6605690164626424 and parameters: {'n_estimators': 465, 'max_depth': 4, 'learning_rate': 0.05680612190600298, 'subsample': 0.8093420558686559, 'colsample_bytree': 0.7369708911051054}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:06:25,283] Trial 10 finished with value: 0.6724626424651752 and parameters: {'n_estimators': 350, 'max_depth': 5, 'learning_rate': 0.03311736949166599, 'subsample': 0.8909937467599877, 'colsample_bytree': 0.8303733101556356}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:06:25,914] Trial 11 finished with value: 0.6967766990291262 and parameters: {'n_estimators': 380, 'max_depth': 5, 'learning_rate': 0.010981227703002, 'subsample': 0.8963118581323058, 'colsample_bytree': 0.8963371826936029}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:06:26,505] Trial 12 finished with value: 0.6787471506964964 and parameters: {'n_estimators': 587, 'max_depth': 3, 'learning_rate': 0.02973925640254988, 'subsample': 0.8692884765349854, 'colsample_bytree': 0.8988011618189465}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:06:26,919] Trial 13 finished with value: 0.7031186154495568 and parameters: {'n_estimators': 296, 'max_depth': 4, 'learning_rate': 0.010413011005893648, 'subsample': 0.860482618301696, 'colsample_bytree': 0.8510074314100841}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:06:27,393] Trial 14 finished with value: 0.6707741663149008 and parameters: {'n_estimators': 289, 'max_depth': 5, 'learning_rate': 0.04514151169290863, 'subsample': 0.857895413263893, 'colsample_bytree': 0.8490601313653239}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:06:27,695] Trial 15 finished with value: 0.7001029970451668 and parameters: {'n_estimators': 213, 'max_depth': 4, 'learning_rate': 0.023351938164489116, 'subsample': 0.8543733335767764, 'colsample_bytree': 0.8188131070313829}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:06:28,087] Trial 16 finished with value: 0.6744381595609963 and parameters: {'n_estimators': 299, 'max_depth': 4, 'learning_rate': 0.04367948501124779, 'subsample': 0.8671855665744578, 'colsample_bytree': 0.8619157836706228}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:06:28,637] Trial 17 finished with value: 0.6977897847192909 and parameters: {'n_estimators': 324, 'max_depth': 5, 'learning_rate': 0.010599273764804039, 'subsample': 0.7277625675105176, 'colsample_bytree': 0.7714702251220459}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:06:28,959] Trial 18 finished with value: 0.6678868720979316 and parameters: {'n_estimators': 241, 'max_depth': 4, 'learning_rate': 0.06786206969422147, 'subsample': 0.8403740921446244, 'colsample_bytree': 0.8100564652678953}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:06:29,572] Trial 19 finished with value: 0.6408881384550442 and parameters: {'n_estimators': 393, 'max_depth': 5, 'learning_rate': 0.09723428668438461, 'subsample': 0.7021978378487542, 'colsample_bytree': 0.8629180257360286}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:06:30,038] Trial 20 finished with value: 0.6954731954411143 and parameters: {'n_estimators': 328, 'max_depth': 4, 'learning_rate': 0.02274258174871161, 'subsample': 0.876603754483263, 'colsample_bytree': 0.7009480239306178}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:06:30,334] Trial 21 finished with value: 0.6985023216547066 and parameters: {'n_estimators': 202, 'max_depth': 4, 'learning_rate': 0.024274307691962267, 'subsample': 0.8479057628120712, 'colsample_bytree': 0.8153898347779356}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:06:30,669] Trial 22 finished with value: 0.6972021950189955 and parameters: {'n_estimators': 237, 'max_depth': 4, 'learning_rate': 0.026348332542640115, 'subsample': 0.8542828376388392, 'colsample_bytree': 0.8266404628456154}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:06:30,997] Trial 23 finished with value: 0.7011093288307302 and parameters: {'n_estimators': 234, 'max_depth': 4, 'learning_rate': 0.017787654107243523, 'subsample': 0.8791467587819954, 'colsample_bytree': 0.7708148758426131}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:06:31,410] Trial 24 finished with value: 0.676153651329675 and parameters: {'n_estimators': 244, 'max_depth': 5, 'learning_rate': 0.040132817457210895, 'subsample': 0.8761284264482079, 'colsample_bytree': 0.7668750708322092}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:06:31,836] Trial 25 finished with value: 0.6984516673701984 and parameters: {'n_estimators': 297, 'max_depth': 4, 'learning_rate': 0.01635713338614355, 'subsample': 0.8973416298412669, 'colsample_bytree': 0.7558039557597273}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:06:32,139] Trial 26 finished with value: 0.7091295905445335 and parameters: {'n_estimators': 264, 'max_depth': 3, 'learning_rate': 0.010743139598731657, 'subsample': 0.834669340930887, 'colsample_bytree': 0.7816329682425044}. Best is trial 26 with value: 0.7091295905445335.
[I 2026-01-11 00:06:32,511] Trial 27 finished with value: 0.7095685943436049 and parameters: {'n_estimators': 317, 'max_depth': 3, 'learning_rate': 0.010955295681655963, 'subsample': 0.8377011536124971, 'colsample_bytree': 0.7928838677943963}. Best is trial 27 with value: 0.7095685943436049.
[I 2026-01-11 00:06:32,870] Trial 28 finished with value: 0.6965774588433937 and parameters: {'n_estimators': 329, 'max_depth': 3, 'learning_rate': 0.03027023712446687, 'subsample': 0.7889826034359546, 'colsample_bytree': 0.8008616799342849}. Best is trial 27 with value: 0.7095685943436049.
[I 2026-01-11 00:06:33,261] Trial 29 finished with value: 0.6860042211903756 and parameters: {'n_estimators': 364, 'max_depth': 3, 'learning_rate': 0.05123211282079642, 'subsample': 0.831105809042793, 'colsample_bytree': 0.7226303028893024}. Best is trial 27 with value: 0.7095685943436049.
[I 2026-01-11 00:06:33,805] Trial 30 finished with value: 0.6842785985647952 and parameters: {'n_estimators': 268, 'max_depth': 6, 'learning_rate': 0.018718426780795744, 'subsample': 0.7989949096553459, 'colsample_bytree': 0.7852999902036104}. Best is trial 27 with value: 0.7095685943436049.
[I 2026-01-11 00:06:34,147] Trial 31 finished with value: 0.7098117349092444 and parameters: {'n_estimators': 312, 'max_depth': 3, 'learning_rate': 0.01041555142712366, 'subsample': 0.8265026055068294, 'colsample_bytree': 0.7470733046160744}. Best is trial 31 with value: 0.7098117349092444.
[I 2026-01-11 00:06:34,539] Trial 32 finished with value: 0.7077990713381174 and parameters: {'n_estimators': 332, 'max_depth': 3, 'learning_rate': 0.014864418904025088, 'subsample': 0.8185350856517829, 'colsample_bytree': 0.7455423783924988}. Best is trial 31 with value: 0.7098117349092444.
[I 2026-01-11 00:06:34,990] Trial 33 finished with value: 0.7022304769945125 and parameters: {'n_estimators': 419, 'max_depth': 3, 'learning_rate': 0.020076514996409743, 'subsample': 0.82361598892196, 'colsample_bytree': 0.7443786803004346}. Best is trial 31 with value: 0.7098117349092444.
[I 2026-01-11 00:06:35,338] Trial 34 finished with value: 0.680209371042634 and parameters: {'n_estimators': 314, 'max_depth': 3, 'learning_rate': 0.06639402717273304, 'subsample': 0.7685850332917236, 'colsample_bytree': 0.7241314979302085}. Best is trial 31 with value: 0.7098117349092444.
[I 2026-01-11 00:06:35,709] Trial 35 finished with value: 0.6979417475728156 and parameters: {'n_estimators': 350, 'max_depth': 3, 'learning_rate': 0.027878018004045213, 'subsample': 0.8057447507329569, 'colsample_bytree': 0.7788899528477934}. Best is trial 31 with value: 0.7098117349092444.
[I 2026-01-11 00:06:36,010] Trial 36 finished with value: 0.7072655128746307 and parameters: {'n_estimators': 278, 'max_depth': 3, 'learning_rate': 0.014672885946710826, 'subsample': 0.8196878926295227, 'colsample_bytree': 0.8007305246909497}. Best is trial 31 with value: 0.7098117349092444.
[I 2026-01-11 00:06:36,400] Trial 37 finished with value: 0.6662152807091599 and parameters: {'n_estimators': 371, 'max_depth': 3, 'learning_rate': 0.08062933146367443, 'subsample': 0.8268728853747789, 'colsample_bytree': 0.7621231047281358}. Best is trial 31 with value: 0.7098117349092444.
[I 2026-01-11 00:06:36,692] Trial 38 finished with value: 0.7005149852258337 and parameters: {'n_estimators': 265, 'max_depth': 3, 'learning_rate': 0.03564640918689765, 'subsample': 0.7776016894687576, 'colsample_bytree': 0.7450668141483597}. Best is trial 31 with value: 0.7098117349092444.
[I 2026-01-11 00:06:37,116] Trial 39 finished with value: 0.7015956099620093 and parameters: {'n_estimators': 413, 'max_depth': 3, 'learning_rate': 0.02079811337925825, 'subsample': 0.8430633421523637, 'colsample_bytree': 0.727525787445404}. Best is trial 31 with value: 0.7098117349092444.
[I 2026-01-11 00:06:37,481] Trial 40 finished with value: 0.7084102997045167 and parameters: {'n_estimators': 342, 'max_depth': 3, 'learning_rate': 0.014549253771309896, 'subsample': 0.8117457601406398, 'colsample_bytree': 0.7152395042890346}. Best is trial 31 with value: 0.7098117349092444.
[I 2026-01-11 00:06:37,856] Trial 41 finished with value: 0.7087344871253694 and parameters: {'n_estimators': 343, 'max_depth': 3, 'learning_rate': 0.015322897174136534, 'subsample': 0.812465197179679, 'colsample_bytree': 0.7186325078380088}. Best is trial 31 with value: 0.7098117349092444.
[I 2026-01-11 00:06:38,246] Trial 42 finished with value: 0.7091667370198397 and parameters: {'n_estimators': 350, 'max_depth': 3, 'learning_rate': 0.010345696154716205, 'subsample': 0.7980696596922362, 'colsample_bytree': 0.713668432240117}. Best is trial 31 with value: 0.7098117349092444.
[I 2026-01-11 00:06:38,592] Trial 43 finished with value: 0.7098252427184466 and parameters: {'n_estimators': 309, 'max_depth': 3, 'learning_rate': 0.010515379562200595, 'subsample': 0.7938172952836617, 'colsample_bytree': 0.7107856782593096}. Best is trial 43 with value: 0.7098252427184466.
[I 2026-01-11 00:06:38,946] Trial 44 finished with value: 0.710487125369354 and parameters: {'n_estimators': 317, 'max_depth': 3, 'learning_rate': 0.010303039133269954, 'subsample': 0.7931683466305235, 'colsample_bytree': 0.7043506757405738}. Best is trial 44 with value: 0.710487125369354.
[I 2026-01-11 00:06:39,279] Trial 45 finished with value: 0.7099299282397636 and parameters: {'n_estimators': 307, 'max_depth': 3, 'learning_rate': 0.010299987260913177, 'subsample': 0.7943526271771272, 'colsample_bytree': 0.7006081635545736}. Best is trial 44 with value: 0.710487125369354.
[I 2026-01-11 00:06:39,610] Trial 46 finished with value: 0.7032536935415787 and parameters: {'n_estimators': 309, 'max_depth': 3, 'learning_rate': 0.022480433544231147, 'subsample': 0.760719844298136, 'colsample_bytree': 0.7005173678700647}. Best is trial 44 with value: 0.710487125369354.
[I 2026-01-11 00:06:39,948] Trial 47 finished with value: 0.6979755170958211 and parameters: {'n_estimators': 311, 'max_depth': 3, 'learning_rate': 0.03230562067162567, 'subsample': 0.7522088715789241, 'colsample_bytree': 0.7358342336706536}. Best is trial 44 with value: 0.710487125369354.
[I 2026-01-11 00:06:40,464] Trial 48 finished with value: 0.7024027015618405 and parameters: {'n_estimators': 491, 'max_depth': 3, 'learning_rate': 0.01856652424446534, 'subsample': 0.7874355001740965, 'colsample_bytree': 0.7074073752289582}. Best is trial 44 with value: 0.710487125369354.

[I 2026-01-11 00:06:40,785] A new study created in memory with name: no-name-4e71a95f-5c1b-4cde-810d-85a35be125c7

[I 2026-01-11 00:06:40,783] Trial 49 finished with value: 0.7029463908822287 and parameters: {'n_estimators': 285, 'max_depth': 3, 'learning_rate': 0.026921786603406883, 'subsample': 0.7820278342387397, 'colsample_bytree': 0.7310381798666995}. Best is trial 44 with value: 0.710487125369354.

✓ Optimization completed!
  Best ROC-AUC: 0.7105
  Best parameters:
    n_estimators: 317
    max_depth: 3
    learning_rate: 0.010303039133269954
    subsample: 0.7931683466305235
    colsample_bytree: 0.7043506757405738

================================================================================
HYPERPARAMETER TUNING - LightGBM
================================================================================

✓ Calculated scale_pos_weight: 5.58

✓ Starting Optuna optimization (50 trials)...
  Objective: Maximize ROC-AUC

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-01-11 00:06:41,606] Trial 0 finished with value: 0.6482566483748415 and parameters: {'n_estimators': 350, 'num_leaves': 49, 'learning_rate': 0.07587945476302646, 'subsample': 0.8197316968394073, 'colsample_bytree': 0.7312037280884873}. Best is trial 0 with value: 0.6482566483748415.
[I 2026-01-11 00:06:41,898] Trial 1 finished with value: 0.6475002110595188 and parameters: {'n_estimators': 262, 'num_leaves': 21, 'learning_rate': 0.08795585311974417, 'subsample': 0.8202230023486418, 'colsample_bytree': 0.8416145155592091}. Best is trial 0 with value: 0.6482566483748415.
[I 2026-01-11 00:06:42,402] Trial 2 finished with value: 0.6596302237230899 and parameters: {'n_estimators': 208, 'num_leaves': 50, 'learning_rate': 0.08491983767203796, 'subsample': 0.7424678221356552, 'colsample_bytree': 0.73636499344142}. Best is trial 2 with value: 0.6596302237230899.
[I 2026-01-11 00:06:42,785] Trial 3 finished with value: 0.6607918953144787 and parameters: {'n_estimators': 273, 'num_leaves': 29, 'learning_rate': 0.05722807884690141, 'subsample': 0.7863890037284231, 'colsample_bytree': 0.7582458280396084}. Best is trial 3 with value: 0.6607918953144787.
[I 2026-01-11 00:06:43,408] Trial 4 finished with value: 0.6615280709159983 and parameters: {'n_estimators': 445, 'num_leaves': 24, 'learning_rate': 0.03629301836816964, 'subsample': 0.7732723686587383, 'colsample_bytree': 0.7912139968434072}. Best is trial 4 with value: 0.6615280709159983.
[I 2026-01-11 00:06:44,150] Trial 5 finished with value: 0.6459535669058674 and parameters: {'n_estimators': 514, 'num_leaves': 26, 'learning_rate': 0.05628109945722505, 'subsample': 0.8184829137724084, 'colsample_bytree': 0.7092900825439995}. Best is trial 4 with value: 0.6615280709159983.
[I 2026-01-11 00:06:44,804] Trial 6 finished with value: 0.6803613338961587 and parameters: {'n_estimators': 443, 'num_leaves': 25, 'learning_rate': 0.015854643368675158, 'subsample': 0.8897771074506666, 'colsample_bytree': 0.8931264066149118}. Best is trial 6 with value: 0.6803613338961587.
[I 2026-01-11 00:06:45,636] Trial 7 finished with value: 0.6717467285774589 and parameters: {'n_estimators': 524, 'num_leaves': 29, 'learning_rate': 0.018790490260574548, 'subsample': 0.8368466053024314, 'colsample_bytree': 0.7880304987479203}. Best is trial 6 with value: 0.6803613338961587.
[I 2026-01-11 00:06:46,073] Trial 8 finished with value: 0.6937374419586323 and parameters: {'n_estimators': 248, 'num_leaves': 35, 'learning_rate': 0.013094966900369657, 'subsample': 0.8818640804157565, 'colsample_bytree': 0.7517559963200033}. Best is trial 8 with value: 0.6937374419586323.
[I 2026-01-11 00:06:46,796] Trial 9 finished with value: 0.6562870409455467 and parameters: {'n_estimators': 465, 'num_leaves': 29, 'learning_rate': 0.05680612190600298, 'subsample': 0.8093420558686559, 'colsample_bytree': 0.7369708911051054}. Best is trial 8 with value: 0.6937374419586323.
[I 2026-01-11 00:06:47,510] Trial 10 finished with value: 0.6614368932038834 and parameters: {'n_estimators': 350, 'num_leaves': 41, 'learning_rate': 0.03311736949166599, 'subsample': 0.8909937467599877, 'colsample_bytree': 0.8303733101556356}. Best is trial 8 with value: 0.6937374419586323.
[I 2026-01-11 00:06:48,281] Trial 11 finished with value: 0.6847716336006753 and parameters: {'n_estimators': 380, 'num_leaves': 37, 'learning_rate': 0.010981227703002, 'subsample': 0.8963118581323058, 'colsample_bytree': 0.8963371826936029}. Best is trial 8 with value: 0.6937374419586323.
[I 2026-01-11 00:06:49,415] Trial 12 finished with value: 0.6755086534402701 and parameters: {'n_estimators': 587, 'num_leaves': 37, 'learning_rate': 0.012110311285307642, 'subsample': 0.8647430292312469, 'colsample_bytree': 0.8915839443678395}. Best is trial 8 with value: 0.6937374419586323.
[I 2026-01-11 00:06:50,079] Trial 13 finished with value: 0.663723089911355 and parameters: {'n_estimators': 340, 'num_leaves': 37, 'learning_rate': 0.032087431857526064, 'subsample': 0.8644928101201926, 'colsample_bytree': 0.8474175474156693}. Best is trial 8 with value: 0.6937374419586323.
[I 2026-01-11 00:06:50,703] Trial 14 finished with value: 0.6769202195018995 and parameters: {'n_estimators': 289, 'num_leaves': 42, 'learning_rate': 0.02269263219331532, 'subsample': 0.857895413263893, 'colsample_bytree': 0.7695266860993165}. Best is trial 8 with value: 0.6937374419586323.
[I 2026-01-11 00:06:51,077] Trial 15 finished with value: 0.6695280709159983 and parameters: {'n_estimators': 213, 'num_leaves': 34, 'learning_rate': 0.044807131716047055, 'subsample': 0.8980992434928939, 'colsample_bytree': 0.8632856305553894}. Best is trial 8 with value: 0.6937374419586323.
[I 2026-01-11 00:06:51,964] Trial 16 finished with value: 0.6684845926551286 and parameters: {'n_estimators': 395, 'num_leaves': 43, 'learning_rate': 0.023850733448436176, 'subsample': 0.8472473098694974, 'colsample_bytree': 0.8219474056669265}. Best is trial 8 with value: 0.6937374419586323.
[I 2026-01-11 00:06:52,540] Trial 17 finished with value: 0.6918834951456311 and parameters: {'n_estimators': 311, 'num_leaves': 34, 'learning_rate': 0.010611433463270861, 'subsample': 0.7277625675105176, 'colsample_bytree': 0.8141230299574098}. Best is trial 8 with value: 0.6937374419586323.
[I 2026-01-11 00:06:53,088] Trial 18 finished with value: 0.6541224145208948 and parameters: {'n_estimators': 302, 'num_leaves': 33, 'learning_rate': 0.06786206969422147, 'subsample': 0.7241172138834286, 'colsample_bytree': 0.8100564652678953}. Best is trial 8 with value: 0.6937374419586323.
[I 2026-01-11 00:06:53,645] Trial 19 finished with value: 0.6524710848459264 and parameters: {'n_estimators': 247, 'num_leaves': 46, 'learning_rate': 0.09723428668438461, 'subsample': 0.7021978378487542, 'colsample_bytree': 0.7703043316266424}. Best is trial 8 with value: 0.6937374419586323.
[I 2026-01-11 00:06:54,204] Trial 20 finished with value: 0.6707370198395948 and parameters: {'n_estimators': 307, 'num_leaves': 32, 'learning_rate': 0.041106652649902285, 'subsample': 0.7533550114519743, 'colsample_bytree': 0.7009480239306178}. Best is trial 8 with value: 0.6937374419586323.
[I 2026-01-11 00:06:55,010] Trial 21 finished with value: 0.6877129590544534 and parameters: {'n_estimators': 384, 'num_leaves': 39, 'learning_rate': 0.010181773912930287, 'subsample': 0.8681074383456624, 'colsample_bytree': 0.8719299750391103}. Best is trial 8 with value: 0.6937374419586323.
[I 2026-01-11 00:06:55,661] Trial 22 finished with value: 0.6727091599831153 and parameters: {'n_estimators': 324, 'num_leaves': 39, 'learning_rate': 0.025501695235817204, 'subsample': 0.875587559488785, 'colsample_bytree': 0.8705566424385562}. Best is trial 8 with value: 0.6937374419586323.
[I 2026-01-11 00:06:56,078] Trial 23 finished with value: 0.6972562262558042 and parameters: {'n_estimators': 239, 'num_leaves': 31, 'learning_rate': 0.010412175659456244, 'subsample': 0.8381664301819819, 'colsample_bytree': 0.8068646281099502}. Best is trial 23 with value: 0.6972562262558042.
[I 2026-01-11 00:06:56,481] Trial 24 finished with value: 0.678443224989447 and parameters: {'n_estimators': 235, 'num_leaves': 31, 'learning_rate': 0.028413276734322705, 'subsample': 0.8344884690330143, 'colsample_bytree': 0.8058202756090669}. Best is trial 23 with value: 0.6972562262558042.
[I 2026-01-11 00:06:56,860] Trial 25 finished with value: 0.6879020683832842 and parameters: {'n_estimators': 200, 'num_leaves': 35, 'learning_rate': 0.018835328318411344, 'subsample': 0.7815104699178844, 'colsample_bytree': 0.781510668772173}. Best is trial 23 with value: 0.6972562262558042.
[I 2026-01-11 00:06:57,231] Trial 26 finished with value: 0.6642195018995356 and parameters: {'n_estimators': 236, 'num_leaves': 30, 'learning_rate': 0.048612511121505386, 'subsample': 0.7946153512031772, 'colsample_bytree': 0.8181163556743234}. Best is trial 23 with value: 0.6972562262558042.
[I 2026-01-11 00:06:57,754] Trial 27 finished with value: 0.6881350780920219 and parameters: {'n_estimators': 271, 'num_leaves': 36, 'learning_rate': 0.015659556787839538, 'subsample': 0.7075402630016802, 'colsample_bytree': 0.7514213473740741}. Best is trial 23 with value: 0.6972562262558042.
[I 2026-01-11 00:06:58,143] Trial 28 finished with value: 0.6648037146475305 and parameters: {'n_estimators': 291, 'num_leaves': 27, 'learning_rate': 0.03792937632479417, 'subsample': 0.7614862788700912, 'colsample_bytree': 0.8034705130428134}. Best is trial 23 with value: 0.6972562262558042.
[I 2026-01-11 00:06:58,901] Trial 29 finished with value: 0.6721992401857324 and parameters: {'n_estimators': 327, 'num_leaves': 46, 'learning_rate': 0.027480466233753956, 'subsample': 0.8433438152801837, 'colsample_bytree': 0.7226303028893024}. Best is trial 23 with value: 0.6972562262558042.
[I 2026-01-11 00:06:59,306] Trial 30 finished with value: 0.6862203461376108 and parameters: {'n_estimators': 237, 'num_leaves': 33, 'learning_rate': 0.02052896343948857, 'subsample': 0.8794347994360143, 'colsample_bytree': 0.7532958029811396}. Best is trial 23 with value: 0.6972562262558042.
[I 2026-01-11 00:06:59,789] Trial 31 finished with value: 0.6901241029970452 and parameters: {'n_estimators': 269, 'num_leaves': 35, 'learning_rate': 0.014646537945817786, 'subsample': 0.7029284093502935, 'colsample_bytree': 0.7470733046160744}. Best is trial 23 with value: 0.6972562262558042.
[I 2026-01-11 00:07:00,335] Trial 32 finished with value: 0.6878818066694807 and parameters: {'n_estimators': 262, 'num_leaves': 39, 'learning_rate': 0.014989487532778296, 'subsample': 0.7189822625632198, 'colsample_bytree': 0.774368893033198}. Best is trial 23 with value: 0.6972562262558042.
[I 2026-01-11 00:07:00,786] Trial 33 finished with value: 0.6840253271422541 and parameters: {'n_estimators': 356, 'num_leaves': 22, 'learning_rate': 0.020076514996409743, 'subsample': 0.7328687305052338, 'colsample_bytree': 0.7239153313844968}. Best is trial 23 with value: 0.6972562262558042.
[I 2026-01-11 00:07:01,174] Trial 34 finished with value: 0.6591506964964119 and parameters: {'n_estimators': 215, 'num_leaves': 35, 'learning_rate': 0.06639402717273304, 'subsample': 0.715058745241993, 'colsample_bytree': 0.7436019515616374}. Best is trial 23 with value: 0.6972562262558042.
[I 2026-01-11 00:07:01,616] Trial 35 finished with value: 0.6956893203883495 and parameters: {'n_estimators': 254, 'num_leaves': 31, 'learning_rate': 0.010087497798163054, 'subsample': 0.7351825253223762, 'colsample_bytree': 0.8400476594302029}. Best is trial 23 with value: 0.6972562262558042.
[I 2026-01-11 00:07:02,021] Trial 36 finished with value: 0.6955002110595186 and parameters: {'n_estimators': 250, 'num_leaves': 27, 'learning_rate': 0.010757366502772574, 'subsample': 0.7417744397540641, 'colsample_bytree': 0.8413665857419929}. Best is trial 23 with value: 0.6972562262558042.
[I 2026-01-11 00:07:02,362] Trial 37 finished with value: 0.6821680033769523 and parameters: {'n_estimators': 223, 'num_leaves': 27, 'learning_rate': 0.029579195380599176, 'subsample': 0.7613033010271494, 'colsample_bytree': 0.8454521992316625}. Best is trial 23 with value: 0.6972562262558042.
[I 2026-01-11 00:07:02,656] Trial 38 finished with value: 0.6503976361333896 and parameters: {'n_estimators': 256, 'num_leaves': 20, 'learning_rate': 0.08616662679622934, 'subsample': 0.7407007095506187, 'colsample_bytree': 0.8308894889992556}. Best is trial 23 with value: 0.6972562262558042.
[I 2026-01-11 00:07:03,032] Trial 39 finished with value: 0.6886314900802026 and parameters: {'n_estimators': 281, 'num_leaves': 23, 'learning_rate': 0.017065204443377207, 'subsample': 0.8226341507605535, 'colsample_bytree': 0.8525131632121659}. Best is trial 23 with value: 0.6972562262558042.
[I 2026-01-11 00:07:03,675] Trial 40 finished with value: 0.6479763613338962 and parameters: {'n_estimators': 423, 'num_leaves': 28, 'learning_rate': 0.07575553905789882, 'subsample': 0.8108339634908518, 'colsample_bytree': 0.7923390246931716}. Best is trial 23 with value: 0.6972562262558042.
[I 2026-01-11 00:07:04,174] Trial 41 finished with value: 0.6939468130012664 and parameters: {'n_estimators': 312, 'num_leaves': 30, 'learning_rate': 0.010020810042814342, 'subsample': 0.7329652406746201, 'colsample_bytree': 0.8326615328992769}. Best is trial 23 with value: 0.6972562262558042.
[I 2026-01-11 00:07:04,516] Trial 42 finished with value: 0.6945175179400589 and parameters: {'n_estimators': 246, 'num_leaves': 25, 'learning_rate': 0.010338782889744616, 'subsample': 0.7478417399155256, 'colsample_bytree': 0.8332155440859016}. Best is trial 23 with value: 0.6972562262558042.
[I 2026-01-11 00:07:04,837] Trial 43 finished with value: 0.6873144786829887 and parameters: {'n_estimators': 227, 'num_leaves': 25, 'learning_rate': 0.023303436705249925, 'subsample': 0.7465165450754617, 'colsample_bytree': 0.8324304946627447}. Best is trial 23 with value: 0.6972562262558042.
[I 2026-01-11 00:07:05,254] Trial 44 finished with value: 0.6952638243984804 and parameters: {'n_estimators': 250, 'num_leaves': 30, 'learning_rate': 0.010296843284634196, 'subsample': 0.7676271123389873, 'colsample_bytree': 0.8555311836900824}. Best is trial 23 with value: 0.6972562262558042.
[I 2026-01-11 00:07:05,548] Trial 45 finished with value: 0.6931295905445336 and parameters: {'n_estimators': 203, 'num_leaves': 25, 'learning_rate': 0.017602088281882988, 'subsample': 0.7698378701119839, 'colsample_bytree': 0.858483839260545}. Best is trial 23 with value: 0.6972562262558042.
[I 2026-01-11 00:07:05,945] Trial 46 finished with value: 0.6953313634444913 and parameters: {'n_estimators': 251, 'num_leaves': 28, 'learning_rate': 0.014414211618582336, 'subsample': 0.7844360652694222, 'colsample_bytree': 0.8823384040886016}. Best is trial 23 with value: 0.6972562262558042.
[I 2026-01-11 00:07:06,437] Trial 47 finished with value: 0.6885369354157873 and parameters: {'n_estimators': 280, 'num_leaves': 31, 'learning_rate': 0.014907642468218336, 'subsample': 0.7872508453334142, 'colsample_bytree': 0.8823673369801222}. Best is trial 23 with value: 0.6972562262558042.
[I 2026-01-11 00:07:07,177] Trial 48 finished with value: 0.6598429717180245 and parameters: {'n_estimators': 491, 'num_leaves': 28, 'learning_rate': 0.03249690607750012, 'subsample': 0.7736087245264718, 'colsample_bytree': 0.8818520757666859}. Best is trial 23 with value: 0.6972562262558042.

[I 2026-01-11 00:07:07,577] A new study created in memory with name: no-name-331f24ad-c294-4b8b-938b-756e6185d78a

[I 2026-01-11 00:07:07,574] Trial 49 finished with value: 0.6844879696074293 and parameters: {'n_estimators': 256, 'num_leaves': 29, 'learning_rate': 0.02153198401278368, 'subsample': 0.8060011989003235, 'colsample_bytree': 0.8565958013758194}. Best is trial 23 with value: 0.6972562262558042.

✓ Optimization completed!
  Best ROC-AUC: 0.6973
  Best parameters:
    n_estimators: 239
    num_leaves: 31
    learning_rate: 0.010412175659456244
    subsample: 0.8381664301819819
    colsample_bytree: 0.8068646281099502

================================================================================
HYPERPARAMETER TUNING - AdaBoost
================================================================================

✓ Using sample_weight to handle imbalance
  Class 0 weight: 0.590
  Class 1 weight: 3.291

✓ Starting Optuna optimization (40 trials)...
  Objective: Maximize ROC-AUC

  0%|          | 0/40 [00:00<?, ?it/s]

[I 2026-01-11 00:07:08,803] Trial 0 finished with value: 0.7106171380329254 and parameters: {'n_estimators': 181, 'learning_rate': 0.951207163345817}. Best is trial 0 with value: 0.7106171380329254.
[I 2026-01-11 00:07:10,749] Trial 1 finished with value: 0.7139535669058674 and parameters: {'n_estimators': 306, 'learning_rate': 0.6026718993550663}. Best is trial 1 with value: 0.7139535669058674.
[I 2026-01-11 00:07:11,467] Trial 2 finished with value: 0.7127412410299704 and parameters: {'n_estimators': 104, 'learning_rate': 0.16443457513284063}. Best is trial 1 with value: 0.7139535669058674.
[I 2026-01-11 00:07:11,924] Trial 3 finished with value: 0.7081992401857323 and parameters: {'n_estimators': 70, 'learning_rate': 0.8675143843171859}. Best is trial 1 with value: 0.7139535669058674.
[I 2026-01-11 00:07:13,677] Trial 4 finished with value: 0.7106542845082313 and parameters: {'n_estimators': 260, 'learning_rate': 0.710991852018085}. Best is trial 1 with value: 0.7139535669058674.
[I 2026-01-11 00:07:14,048] Trial 5 finished with value: 0.7080658505698607 and parameters: {'n_estimators': 57, 'learning_rate': 0.9702107536403743}. Best is trial 1 with value: 0.7139535669058674.
[I 2026-01-11 00:07:16,362] Trial 6 finished with value: 0.7174014352047278 and parameters: {'n_estimators': 342, 'learning_rate': 0.2202157195714934}. Best is trial 6 with value: 0.7174014352047278.
[I 2026-01-11 00:07:17,112] Trial 7 finished with value: 0.7129523005487548 and parameters: {'n_estimators': 113, 'learning_rate': 0.1915704647548995}. Best is trial 6 with value: 0.7174014352047278.
[I 2026-01-11 00:07:18,133] Trial 8 finished with value: 0.7172157028281976 and parameters: {'n_estimators': 156, 'learning_rate': 0.5295088673159155}. Best is trial 6 with value: 0.7174014352047278.
[I 2026-01-11 00:07:19,490] Trial 9 finished with value: 0.7173254537779654 and parameters: {'n_estimators': 201, 'learning_rate': 0.2983168487960615}. Best is trial 6 with value: 0.7174014352047278.
[I 2026-01-11 00:07:22,164] Trial 10 finished with value: 0.7074596876319122 and parameters: {'n_estimators': 393, 'learning_rate': 0.015937211126259176}. Best is trial 6 with value: 0.7174014352047278.
[I 2026-01-11 00:07:24,522] Trial 11 finished with value: 0.7175246939636978 and parameters: {'n_estimators': 362, 'learning_rate': 0.3300175907375913}. Best is trial 11 with value: 0.7175246939636978.
[I 2026-01-11 00:07:27,075] Trial 12 finished with value: 0.7170164626424652 and parameters: {'n_estimators': 394, 'learning_rate': 0.3635040930508199}. Best is trial 11 with value: 0.7175246939636978.
[I 2026-01-11 00:07:29,310] Trial 13 finished with value: 0.7186036302237231 and parameters: {'n_estimators': 333, 'learning_rate': 0.3985283631816061}. Best is trial 13 with value: 0.7186036302237231.
[I 2026-01-11 00:07:31,092] Trial 14 finished with value: 0.7193870831574504 and parameters: {'n_estimators': 270, 'learning_rate': 0.4070687789345023}. Best is trial 14 with value: 0.7193870831574504.
[I 2026-01-11 00:07:32,824] Trial 15 finished with value: 0.7174926129168424 and parameters: {'n_estimators': 257, 'learning_rate': 0.4455497124829996}. Best is trial 14 with value: 0.7193870831574504.
[I 2026-01-11 00:07:34,809] Trial 16 finished with value: 0.7138455044322499 and parameters: {'n_estimators': 306, 'learning_rate': 0.6101802832707559}. Best is trial 14 with value: 0.7193870831574504.
[I 2026-01-11 00:07:36,595] Trial 17 finished with value: 0.7171853102574925 and parameters: {'n_estimators': 267, 'learning_rate': 0.45524990159794043}. Best is trial 14 with value: 0.7193870831574504.
[I 2026-01-11 00:07:38,635] Trial 18 finished with value: 0.7093271422541156 and parameters: {'n_estimators': 313, 'learning_rate': 0.7699497377237832}. Best is trial 14 with value: 0.7193870831574504.
[I 2026-01-11 00:07:40,221] Trial 19 finished with value: 0.7099012241452088 and parameters: {'n_estimators': 239, 'learning_rate': 0.04466371655238177}. Best is trial 14 with value: 0.7193870831574504.
[I 2026-01-11 00:07:42,440] Trial 20 finished with value: 0.7138792739552553 and parameters: {'n_estimators': 342, 'learning_rate': 0.5542053099029007}. Best is trial 14 with value: 0.7193870831574504.
[I 2026-01-11 00:07:44,728] Trial 21 finished with value: 0.7177138032925284 and parameters: {'n_estimators': 355, 'learning_rate': 0.35986217694369105}. Best is trial 14 with value: 0.7193870831574504.
[I 2026-01-11 00:07:46,593] Trial 22 finished with value: 0.7185647952722667 and parameters: {'n_estimators': 288, 'learning_rate': 0.4187354253190594}. Best is trial 14 with value: 0.7193870831574504.
[I 2026-01-11 00:07:48,588] Trial 23 finished with value: 0.7169995778809624 and parameters: {'n_estimators': 294, 'learning_rate': 0.4501879782883536}. Best is trial 14 with value: 0.7193870831574504.
[I 2026-01-11 00:07:50,001] Trial 24 finished with value: 0.7172207682566484 and parameters: {'n_estimators': 218, 'learning_rate': 0.26387858614048637}. Best is trial 14 with value: 0.7193870831574504.
[I 2026-01-11 00:07:51,839] Trial 25 finished with value: 0.7157281553398057 and parameters: {'n_estimators': 294, 'learning_rate': 0.11650459175692512}. Best is trial 14 with value: 0.7193870831574504.
[I 2026-01-11 00:07:53,578] Trial 26 finished with value: 0.7183064584212746 and parameters: {'n_estimators': 273, 'learning_rate': 0.39901703124994253}. Best is trial 14 with value: 0.7193870831574504.
[I 2026-01-11 00:07:55,035] Trial 27 finished with value: 0.7116572393414942 and parameters: {'n_estimators': 232, 'learning_rate': 0.688649562047645}. Best is trial 14 with value: 0.7193870831574504.
[I 2026-01-11 00:07:57,196] Trial 28 finished with value: 0.716325875897003 and parameters: {'n_estimators': 334, 'learning_rate': 0.49311629573249377}. Best is trial 14 with value: 0.7193870831574504.
[I 2026-01-11 00:07:59,508] Trial 29 finished with value: 0.7133862389193751 and parameters: {'n_estimators': 370, 'learning_rate': 0.5761515042400334}. Best is trial 14 with value: 0.7193870831574504.
[I 2026-01-11 00:08:00,581] Trial 30 finished with value: 0.7164812157028282 and parameters: {'n_estimators': 167, 'learning_rate': 0.2646659027795909}. Best is trial 14 with value: 0.7193870831574504.
[I 2026-01-11 00:08:02,308] Trial 31 finished with value: 0.7200726044744618 and parameters: {'n_estimators': 276, 'learning_rate': 0.40598089238987783}. Best is trial 31 with value: 0.7200726044744618.
[I 2026-01-11 00:08:04,038] Trial 32 finished with value: 0.7182237230899113 and parameters: {'n_estimators': 281, 'learning_rate': 0.3910996108161097}. Best is trial 31 with value: 0.7200726044744618.
[I 2026-01-11 00:08:06,163] Trial 33 finished with value: 0.7187674124102996 and parameters: {'n_estimators': 323, 'learning_rate': 0.4268712957271718}. Best is trial 31 with value: 0.7200726044744618.
[I 2026-01-11 00:08:08,094] Trial 34 finished with value: 0.7132460953989026 and parameters: {'n_estimators': 313, 'learning_rate': 0.6347211671033348}. Best is trial 31 with value: 0.7200726044744618.
[I 2026-01-11 00:08:10,143] Trial 35 finished with value: 0.7162161249472352 and parameters: {'n_estimators': 324, 'learning_rate': 0.4977072065757854}. Best is trial 31 with value: 0.7200726044744618.
[I 2026-01-11 00:08:11,728] Trial 36 finished with value: 0.7170299704516673 and parameters: {'n_estimators': 254, 'learning_rate': 0.29370647405642347}. Best is trial 31 with value: 0.7200726044744618.
[I 2026-01-11 00:08:14,009] Trial 37 finished with value: 0.7173457154917686 and parameters: {'n_estimators': 370, 'learning_rate': 0.1510372460852991}. Best is trial 31 with value: 0.7200726044744618.
[I 2026-01-11 00:08:15,556] Trial 38 finished with value: 0.70843056141832 and parameters: {'n_estimators': 244, 'learning_rate': 0.8377120866291334}. Best is trial 31 with value: 0.7200726044744618.
[I 2026-01-11 00:08:16,975] Trial 39 finished with value: 0.7167530603630224 and parameters: {'n_estimators': 217, 'learning_rate': 0.22050405930100458}. Best is trial 31 with value: 0.7200726044744618.

✓ Optimization completed!
  Best ROC-AUC: 0.7201
  Best parameters:
    n_estimators: 276
    learning_rate: 0.40598089238987783

================================================================================
TRAINING BASE ENSEMBLE MODELS
================================================================================

================================================================================
Training: XGBoost
================================================================================
  Running 5-fold cross-validation...

  Cross-Validation Results (mean ± std):
    Accuracy:  0.6805 ± 0.0260
    Precision: 0.2621 ± 0.0203
    Recall:    0.6000 ± 0.0188
    F1-Score:  0.3642 ± 0.0182
    ROC-AUC:   0.7085 ± 0.0192

  Test Set Performance:
    Accuracy:  0.6580
    Precision: 0.2395
    Recall:    0.5736
    F1-Score:  0.3379
    ROC-AUC:   0.6752

================================================================================
Training: LightGBM
================================================================================
  Running 5-fold cross-validation...

  Cross-Validation Results (mean ± std):
    Accuracy:  0.7363 ± 0.0165
    Precision: 0.2777 ± 0.0101
    Recall:    0.4563 ± 0.0434
    F1-Score:  0.3440 ± 0.0104
    ROC-AUC:   0.6973 ± 0.0186

  Test Set Performance:
    Accuracy:  0.7170
    Precision: 0.2419
    Recall:    0.4031
    F1-Score:  0.3023
    ROC-AUC:   0.6519

================================================================================
Training: AdaBoost
================================================================================
  Running 5-fold cross-validation...

  Cross-Validation Results (mean ± std):
    Accuracy:  0.6676 ± 0.0249
    Precision: 0.2594 ± 0.0182
    Recall:    0.6350 ± 0.0340
    F1-Score:  0.3678 ± 0.0187
    ROC-AUC:   0.7201 ± 0.0209

  Test Set Performance:
    Accuracy:  0.6545
    Precision: 0.2389
    Recall:    0.5814
    F1-Score:  0.3386
    ROC-AUC:   0.6779

================================================================================
CREATING STACKING ENSEMBLE
================================================================================

✓ Training stacking ensemble...
  Base estimators: 3
  Meta-learner: Logistic Regression
✓ Stacking ensemble trained successfully!

================================================================================
GENERATING VISUALIZATIONS
================================================================================

✓ ROC curves saved: roc_curves_comparison.png
✓ Confusion matrices saved: confusion_matrices.png

================================================================================
FEATURE IMPORTANCE & INTERPRETABILITY
================================================================================

================================================================================
Feature Importance Analysis - XGBoost
================================================================================

Top 10 Most Important Features:
  hypertension             : 0.2822
  age_group_code           : 0.2553
  pulse_pressure           : 0.1225
  cigarettes_per_day       : 0.0916
  glucose                  : 0.0669
  bmi                      : 0.0644
  total_cholesterol        : 0.0632
  heart_rate               : 0.0539

✓ Feature importance plot saved: feature_importance_xgboost.png

================================================================================
SHAP Analysis - XGBoost
================================================================================

✓ Creating SHAP explainer...
✓ Calculating SHAP values for 500 samples...
✓ SHAP summary plot saved: shap_summary_xgboost.png

Top 10 Features by SHAP Importance:
  age_group_code           : 0.3540
  cigarettes_per_day       : 0.2074
  pulse_pressure           : 0.2003
  hypertension             : 0.1295
  bmi                      : 0.0775
  total_cholesterol        : 0.0627
  glucose                  : 0.0523
  heart_rate               : 0.0309

================================================================================
Feature Importance Analysis - LightGBM
================================================================================

Top 10 Most Important Features:
  total_cholesterol        : 1382.0000
  bmi                      : 1296.0000
  pulse_pressure           : 1139.0000
  heart_rate               : 1115.0000
  glucose                  : 1052.0000
  cigarettes_per_day       : 603.0000
  age_group_code           : 444.0000
  hypertension             : 139.0000

✓ Feature importance plot saved: feature_importance_lightgbm.png

================================================================================
SHAP Analysis - LightGBM
================================================================================

✓ Creating SHAP explainer...
✓ Calculating SHAP values for 500 samples...
✓ SHAP summary plot saved: shap_summary_lightgbm.png

Top 10 Features by SHAP Importance:
  age_group_code           : 0.5109
  cigarettes_per_day       : 0.2746
  pulse_pressure           : 0.2220
  total_cholesterol        : 0.1331
  hypertension             : 0.1210
  bmi                      : 0.1180
  heart_rate               : 0.0874
  glucose                  : 0.0713

================================================================================
Feature Importance Analysis - AdaBoost
================================================================================

Top 10 Most Important Features:
  glucose                  : 0.3350
  age_group_code           : 0.2296
  total_cholesterol        : 0.1575
  pulse_pressure           : 0.1174
  cigarettes_per_day       : 0.0978
  hypertension             : 0.0352
  bmi                      : 0.0275
  heart_rate               : 0.0000

✓ Feature importance plot saved: feature_importance_adaboost.png

================================================================================
SHAP Analysis - AdaBoost
================================================================================

✓ Creating SHAP explainer...
✗ SHAP analysis failed: Model type not yet supported by TreeExplainer: <class 'sklearn.ensemble._weight_boosting.AdaBoostClassifier'>

================================================================================
LEARNING AND VALIDATION CURVES
================================================================================

================================================================================
Learning Curves - XGBoost
================================================================================
✓ Learning curves saved: learning_curves_xgboost.png

================================================================================
Validation Curve - XGBoost
================================================================================
✓ Validation curve saved: validation_curve_xgboost.png

================================================================================
Learning Curves - LightGBM
================================================================================
✓ Learning curves saved: learning_curves_lightgbm.png

================================================================================
Validation Curve - LightGBM
================================================================================
✓ Validation curve saved: validation_curve_lightgbm.png

================================================================================
Learning Curves - AdaBoost
================================================================================
✓ Learning curves saved: learning_curves_adaboost.png

================================================================================
Validation Curve - AdaBoost
================================================================================

[I 2026-01-11 00:08:47,654] A new study created in memory with name: no-name-a356cf98-a94d-4837-9d49-9b1d7e3a210c

✓ Validation curve saved: validation_curve_adaboost.png

================================================================================
CREATING MODEL COMPARISON TABLE
================================================================================

✓ Model comparison saved: model_comparison_boosting.csv

Model Comparison Table:
   Model  Accuracy  Precision   Recall  F1-Score  ROC-AUC
Stacking  0.653302   0.246154 0.620155  0.352423 0.685696
AdaBoost  0.654481   0.238854 0.581395  0.338600 0.677950
 XGBoost  0.658019   0.239482 0.573643  0.337900 0.675163
LightGBM  0.716981   0.241860 0.403101  0.302326 0.651853

================================================================================
CORONARY HEART DISEASE PREDICTION PROJECT
Advanced Models & Model Selection - Collaborator 5
================================================================================
Start Time: 2026-01-11 00:08:47
================================================================================
================================================================================
STEP 1: LOADING PRE-SPLIT DATA
================================================================================

✓ Loading training data from: ../data/processed\train_standard_scaled.csv
  Shape: (3390, 9)

✓ Loading test data from: ../data/processed\test_standard_scaled.csv
  Shape: (848, 9)

✓ Target column: TenYearCHD

✓ Data split information:
  Training set: (3390, 8)
  Test set: (848, 8)

✓ Feature consistency verified

✓ Training Set Class Distribution:
  Class 0 (No CHD): 2875 (84.81%)
  Class 1 (CHD): 515 (15.19%)
  Imbalance Ratio: 5.58:1

✓ Test Set Class Distribution:
  Class 0 (No CHD): 719 (84.79%)
  Class 1 (CHD): 129 (15.21%)
  Imbalance Ratio: 5.57:1

✓ No categorical variables found (all numeric)

✓ Features (8):
   1. bmi
   2. hypertension
   3. pulse_pressure
   4. cigarettes_per_day
   5. total_cholesterol
   6. glucose
   7. heart_rate
   8. age_group_code

================================================================================
HYPERPARAMETER TUNING - XGBoost
================================================================================

✓ Calculated scale_pos_weight: 5.58

✓ Starting Optuna optimization (50 trials)...
  Objective: Maximize ROC-AUC

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-01-11 00:08:48,399] Trial 0 finished with value: 0.6456395103419164 and parameters: {'n_estimators': 350, 'max_depth': 6, 'learning_rate': 0.07587945476302646, 'subsample': 0.8197316968394073, 'colsample_bytree': 0.7312037280884873}. Best is trial 0 with value: 0.6456395103419164.
[I 2026-01-11 00:08:48,693] Trial 1 finished with value: 0.6734250738708316 and parameters: {'n_estimators': 262, 'max_depth': 3, 'learning_rate': 0.08795585311974417, 'subsample': 0.8202230023486418, 'colsample_bytree': 0.8416145155592091}. Best is trial 1 with value: 0.6734250738708316.
[I 2026-01-11 00:08:49,094] Trial 2 finished with value: 0.657668214436471 and parameters: {'n_estimators': 208, 'max_depth': 6, 'learning_rate': 0.08491983767203796, 'subsample': 0.7424678221356552, 'colsample_bytree': 0.73636499344142}. Best is trial 1 with value: 0.6734250738708316.
[I 2026-01-11 00:08:49,453] Trial 3 finished with value: 0.6770417897847193 and parameters: {'n_estimators': 273, 'max_depth': 4, 'learning_rate': 0.05722807884690141, 'subsample': 0.7863890037284231, 'colsample_bytree': 0.7582458280396084}. Best is trial 3 with value: 0.6770417897847193.
[I 2026-01-11 00:08:49,920] Trial 4 finished with value: 0.6836403545799915 and parameters: {'n_estimators': 445, 'max_depth': 3, 'learning_rate': 0.03629301836816964, 'subsample': 0.7732723686587383, 'colsample_bytree': 0.7912139968434072}. Best is trial 4 with value: 0.6836403545799915.
[I 2026-01-11 00:08:50,474] Trial 5 finished with value: 0.6694504010130856 and parameters: {'n_estimators': 514, 'max_depth': 3, 'learning_rate': 0.05628109945722505, 'subsample': 0.8184829137724084, 'colsample_bytree': 0.7092900825439995}. Best is trial 4 with value: 0.6836403545799915.
[I 2026-01-11 00:08:50,928] Trial 6 finished with value: 0.6994681300126636 and parameters: {'n_estimators': 443, 'max_depth': 3, 'learning_rate': 0.015854643368675158, 'subsample': 0.8897771074506666, 'colsample_bytree': 0.8931264066149118}. Best is trial 6 with value: 0.6994681300126636.
[I 2026-01-11 00:08:51,612] Trial 7 finished with value: 0.688216124947235 and parameters: {'n_estimators': 524, 'max_depth': 4, 'learning_rate': 0.018790490260574548, 'subsample': 0.8368466053024314, 'colsample_bytree': 0.7880304987479203}. Best is trial 6 with value: 0.6994681300126636.
[I 2026-01-11 00:08:51,946] Trial 8 finished with value: 0.7059113550021106 and parameters: {'n_estimators': 248, 'max_depth': 4, 'learning_rate': 0.013094966900369657, 'subsample': 0.8818640804157565, 'colsample_bytree': 0.7517559963200033}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:08:52,574] Trial 9 finished with value: 0.6605690164626424 and parameters: {'n_estimators': 465, 'max_depth': 4, 'learning_rate': 0.05680612190600298, 'subsample': 0.8093420558686559, 'colsample_bytree': 0.7369708911051054}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:08:53,161] Trial 10 finished with value: 0.6724626424651752 and parameters: {'n_estimators': 350, 'max_depth': 5, 'learning_rate': 0.03311736949166599, 'subsample': 0.8909937467599877, 'colsample_bytree': 0.8303733101556356}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:08:53,791] Trial 11 finished with value: 0.6967766990291262 and parameters: {'n_estimators': 380, 'max_depth': 5, 'learning_rate': 0.010981227703002, 'subsample': 0.8963118581323058, 'colsample_bytree': 0.8963371826936029}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:08:54,433] Trial 12 finished with value: 0.6787471506964964 and parameters: {'n_estimators': 587, 'max_depth': 3, 'learning_rate': 0.02973925640254988, 'subsample': 0.8692884765349854, 'colsample_bytree': 0.8988011618189465}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:08:54,881] Trial 13 finished with value: 0.7031186154495568 and parameters: {'n_estimators': 296, 'max_depth': 4, 'learning_rate': 0.010413011005893648, 'subsample': 0.860482618301696, 'colsample_bytree': 0.8510074314100841}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:08:55,368] Trial 14 finished with value: 0.6707741663149008 and parameters: {'n_estimators': 289, 'max_depth': 5, 'learning_rate': 0.04514151169290863, 'subsample': 0.857895413263893, 'colsample_bytree': 0.8490601313653239}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:08:55,677] Trial 15 finished with value: 0.7001029970451668 and parameters: {'n_estimators': 213, 'max_depth': 4, 'learning_rate': 0.023351938164489116, 'subsample': 0.8543733335767764, 'colsample_bytree': 0.8188131070313829}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:08:56,082] Trial 16 finished with value: 0.6744381595609963 and parameters: {'n_estimators': 299, 'max_depth': 4, 'learning_rate': 0.04367948501124779, 'subsample': 0.8671855665744578, 'colsample_bytree': 0.8619157836706228}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:08:56,647] Trial 17 finished with value: 0.6977897847192909 and parameters: {'n_estimators': 324, 'max_depth': 5, 'learning_rate': 0.010599273764804039, 'subsample': 0.7277625675105176, 'colsample_bytree': 0.7714702251220459}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:08:56,983] Trial 18 finished with value: 0.6678868720979316 and parameters: {'n_estimators': 241, 'max_depth': 4, 'learning_rate': 0.06786206969422147, 'subsample': 0.8403740921446244, 'colsample_bytree': 0.8100564652678953}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:08:57,655] Trial 19 finished with value: 0.6408881384550442 and parameters: {'n_estimators': 393, 'max_depth': 5, 'learning_rate': 0.09723428668438461, 'subsample': 0.7021978378487542, 'colsample_bytree': 0.8629180257360286}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:08:58,094] Trial 20 finished with value: 0.6954731954411143 and parameters: {'n_estimators': 328, 'max_depth': 4, 'learning_rate': 0.02274258174871161, 'subsample': 0.876603754483263, 'colsample_bytree': 0.7009480239306178}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:08:58,456] Trial 21 finished with value: 0.6985023216547066 and parameters: {'n_estimators': 202, 'max_depth': 4, 'learning_rate': 0.024274307691962267, 'subsample': 0.8479057628120712, 'colsample_bytree': 0.8153898347779356}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:08:58,824] Trial 22 finished with value: 0.6972021950189955 and parameters: {'n_estimators': 237, 'max_depth': 4, 'learning_rate': 0.026348332542640115, 'subsample': 0.8542828376388392, 'colsample_bytree': 0.8266404628456154}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:08:59,151] Trial 23 finished with value: 0.7011093288307302 and parameters: {'n_estimators': 234, 'max_depth': 4, 'learning_rate': 0.017787654107243523, 'subsample': 0.8791467587819954, 'colsample_bytree': 0.7708148758426131}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:08:59,551] Trial 24 finished with value: 0.676153651329675 and parameters: {'n_estimators': 244, 'max_depth': 5, 'learning_rate': 0.040132817457210895, 'subsample': 0.8761284264482079, 'colsample_bytree': 0.7668750708322092}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:08:59,952] Trial 25 finished with value: 0.6984516673701984 and parameters: {'n_estimators': 297, 'max_depth': 4, 'learning_rate': 0.01635713338614355, 'subsample': 0.8973416298412669, 'colsample_bytree': 0.7558039557597273}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:09:00,328] Trial 26 finished with value: 0.7091295905445335 and parameters: {'n_estimators': 264, 'max_depth': 3, 'learning_rate': 0.010743139598731657, 'subsample': 0.834669340930887, 'colsample_bytree': 0.7816329682425044}. Best is trial 26 with value: 0.7091295905445335.
[I 2026-01-11 00:09:00,725] Trial 27 finished with value: 0.7095685943436049 and parameters: {'n_estimators': 317, 'max_depth': 3, 'learning_rate': 0.010955295681655963, 'subsample': 0.8377011536124971, 'colsample_bytree': 0.7928838677943963}. Best is trial 27 with value: 0.7095685943436049.
[I 2026-01-11 00:09:01,080] Trial 28 finished with value: 0.6965774588433937 and parameters: {'n_estimators': 329, 'max_depth': 3, 'learning_rate': 0.03027023712446687, 'subsample': 0.7889826034359546, 'colsample_bytree': 0.8008616799342849}. Best is trial 27 with value: 0.7095685943436049.
[I 2026-01-11 00:09:01,468] Trial 29 finished with value: 0.6860042211903756 and parameters: {'n_estimators': 364, 'max_depth': 3, 'learning_rate': 0.05123211282079642, 'subsample': 0.831105809042793, 'colsample_bytree': 0.7226303028893024}. Best is trial 27 with value: 0.7095685943436049.
[I 2026-01-11 00:09:02,059] Trial 30 finished with value: 0.6842785985647952 and parameters: {'n_estimators': 268, 'max_depth': 6, 'learning_rate': 0.018718426780795744, 'subsample': 0.7989949096553459, 'colsample_bytree': 0.7852999902036104}. Best is trial 27 with value: 0.7095685943436049.
[I 2026-01-11 00:09:02,401] Trial 31 finished with value: 0.7098117349092444 and parameters: {'n_estimators': 312, 'max_depth': 3, 'learning_rate': 0.01041555142712366, 'subsample': 0.8265026055068294, 'colsample_bytree': 0.7470733046160744}. Best is trial 31 with value: 0.7098117349092444.
[I 2026-01-11 00:09:02,769] Trial 32 finished with value: 0.7077990713381174 and parameters: {'n_estimators': 332, 'max_depth': 3, 'learning_rate': 0.014864418904025088, 'subsample': 0.8185350856517829, 'colsample_bytree': 0.7455423783924988}. Best is trial 31 with value: 0.7098117349092444.
[I 2026-01-11 00:09:03,202] Trial 33 finished with value: 0.7022304769945125 and parameters: {'n_estimators': 419, 'max_depth': 3, 'learning_rate': 0.020076514996409743, 'subsample': 0.82361598892196, 'colsample_bytree': 0.7443786803004346}. Best is trial 31 with value: 0.7098117349092444.
[I 2026-01-11 00:09:03,528] Trial 34 finished with value: 0.680209371042634 and parameters: {'n_estimators': 314, 'max_depth': 3, 'learning_rate': 0.06639402717273304, 'subsample': 0.7685850332917236, 'colsample_bytree': 0.7241314979302085}. Best is trial 31 with value: 0.7098117349092444.
[I 2026-01-11 00:09:03,900] Trial 35 finished with value: 0.6979417475728156 and parameters: {'n_estimators': 350, 'max_depth': 3, 'learning_rate': 0.027878018004045213, 'subsample': 0.8057447507329569, 'colsample_bytree': 0.7788899528477934}. Best is trial 31 with value: 0.7098117349092444.
[I 2026-01-11 00:09:04,213] Trial 36 finished with value: 0.7072655128746307 and parameters: {'n_estimators': 278, 'max_depth': 3, 'learning_rate': 0.014672885946710826, 'subsample': 0.8196878926295227, 'colsample_bytree': 0.8007305246909497}. Best is trial 31 with value: 0.7098117349092444.
[I 2026-01-11 00:09:04,623] Trial 37 finished with value: 0.6662152807091599 and parameters: {'n_estimators': 371, 'max_depth': 3, 'learning_rate': 0.08062933146367443, 'subsample': 0.8268728853747789, 'colsample_bytree': 0.7621231047281358}. Best is trial 31 with value: 0.7098117349092444.
[I 2026-01-11 00:09:04,920] Trial 38 finished with value: 0.7005149852258337 and parameters: {'n_estimators': 265, 'max_depth': 3, 'learning_rate': 0.03564640918689765, 'subsample': 0.7776016894687576, 'colsample_bytree': 0.7450668141483597}. Best is trial 31 with value: 0.7098117349092444.
[I 2026-01-11 00:09:05,403] Trial 39 finished with value: 0.7015956099620093 and parameters: {'n_estimators': 413, 'max_depth': 3, 'learning_rate': 0.02079811337925825, 'subsample': 0.8430633421523637, 'colsample_bytree': 0.727525787445404}. Best is trial 31 with value: 0.7098117349092444.
[I 2026-01-11 00:09:05,782] Trial 40 finished with value: 0.7084102997045167 and parameters: {'n_estimators': 342, 'max_depth': 3, 'learning_rate': 0.014549253771309896, 'subsample': 0.8117457601406398, 'colsample_bytree': 0.7152395042890346}. Best is trial 31 with value: 0.7098117349092444.
[I 2026-01-11 00:09:06,167] Trial 41 finished with value: 0.7087344871253694 and parameters: {'n_estimators': 343, 'max_depth': 3, 'learning_rate': 0.015322897174136534, 'subsample': 0.812465197179679, 'colsample_bytree': 0.7186325078380088}. Best is trial 31 with value: 0.7098117349092444.
[I 2026-01-11 00:09:06,555] Trial 42 finished with value: 0.7091667370198397 and parameters: {'n_estimators': 350, 'max_depth': 3, 'learning_rate': 0.010345696154716205, 'subsample': 0.7980696596922362, 'colsample_bytree': 0.713668432240117}. Best is trial 31 with value: 0.7098117349092444.
[I 2026-01-11 00:09:06,896] Trial 43 finished with value: 0.7098252427184466 and parameters: {'n_estimators': 309, 'max_depth': 3, 'learning_rate': 0.010515379562200595, 'subsample': 0.7938172952836617, 'colsample_bytree': 0.7107856782593096}. Best is trial 43 with value: 0.7098252427184466.
[I 2026-01-11 00:09:07,257] Trial 44 finished with value: 0.710487125369354 and parameters: {'n_estimators': 317, 'max_depth': 3, 'learning_rate': 0.010303039133269954, 'subsample': 0.7931683466305235, 'colsample_bytree': 0.7043506757405738}. Best is trial 44 with value: 0.710487125369354.
[I 2026-01-11 00:09:07,585] Trial 45 finished with value: 0.7099299282397636 and parameters: {'n_estimators': 307, 'max_depth': 3, 'learning_rate': 0.010299987260913177, 'subsample': 0.7943526271771272, 'colsample_bytree': 0.7006081635545736}. Best is trial 44 with value: 0.710487125369354.
[I 2026-01-11 00:09:07,915] Trial 46 finished with value: 0.7032536935415787 and parameters: {'n_estimators': 309, 'max_depth': 3, 'learning_rate': 0.022480433544231147, 'subsample': 0.760719844298136, 'colsample_bytree': 0.7005173678700647}. Best is trial 44 with value: 0.710487125369354.
[I 2026-01-11 00:09:08,258] Trial 47 finished with value: 0.6979755170958211 and parameters: {'n_estimators': 311, 'max_depth': 3, 'learning_rate': 0.03230562067162567, 'subsample': 0.7522088715789241, 'colsample_bytree': 0.7358342336706536}. Best is trial 44 with value: 0.710487125369354.
[I 2026-01-11 00:09:08,758] Trial 48 finished with value: 0.7024027015618405 and parameters: {'n_estimators': 491, 'max_depth': 3, 'learning_rate': 0.01856652424446534, 'subsample': 0.7874355001740965, 'colsample_bytree': 0.7074073752289582}. Best is trial 44 with value: 0.710487125369354.

[I 2026-01-11 00:09:09,076] A new study created in memory with name: no-name-d02fc85d-7cd7-444f-bf96-13ac07d3d2b2

[I 2026-01-11 00:09:09,073] Trial 49 finished with value: 0.7029463908822287 and parameters: {'n_estimators': 285, 'max_depth': 3, 'learning_rate': 0.026921786603406883, 'subsample': 0.7820278342387397, 'colsample_bytree': 0.7310381798666995}. Best is trial 44 with value: 0.710487125369354.

✓ Optimization completed!
  Best ROC-AUC: 0.7105
  Best parameters:
    n_estimators: 317
    max_depth: 3
    learning_rate: 0.010303039133269954
    subsample: 0.7931683466305235
    colsample_bytree: 0.7043506757405738

================================================================================
HYPERPARAMETER TUNING - LightGBM
================================================================================

✓ Calculated scale_pos_weight: 5.58

✓ Starting Optuna optimization (50 trials)...
  Objective: Maximize ROC-AUC

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-01-11 00:09:09,945] Trial 0 finished with value: 0.6562566483748417 and parameters: {'n_estimators': 350, 'num_leaves': 49, 'learning_rate': 0.07587945476302646, 'subsample': 0.8197316968394073, 'colsample_bytree': 0.7312037280884873}. Best is trial 0 with value: 0.6562566483748417.
[I 2026-01-11 00:09:10,299] Trial 1 finished with value: 0.6445453777965386 and parameters: {'n_estimators': 262, 'num_leaves': 21, 'learning_rate': 0.08795585311974417, 'subsample': 0.8202230023486418, 'colsample_bytree': 0.8416145155592091}. Best is trial 0 with value: 0.6562566483748417.
[I 2026-01-11 00:09:10,859] Trial 2 finished with value: 0.6574926129168425 and parameters: {'n_estimators': 208, 'num_leaves': 50, 'learning_rate': 0.08491983767203796, 'subsample': 0.7424678221356552, 'colsample_bytree': 0.73636499344142}. Best is trial 2 with value: 0.6574926129168425.
[I 2026-01-11 00:09:11,316] Trial 3 finished with value: 0.6551625158294639 and parameters: {'n_estimators': 273, 'num_leaves': 29, 'learning_rate': 0.05722807884690141, 'subsample': 0.7863890037284231, 'colsample_bytree': 0.7582458280396084}. Best is trial 2 with value: 0.6574926129168425.
[I 2026-01-11 00:09:11,965] Trial 4 finished with value: 0.6610181511186155 and parameters: {'n_estimators': 445, 'num_leaves': 24, 'learning_rate': 0.03629301836816964, 'subsample': 0.7732723686587383, 'colsample_bytree': 0.7912139968434072}. Best is trial 4 with value: 0.6610181511186155.
[I 2026-01-11 00:09:12,731] Trial 5 finished with value: 0.6462473617560152 and parameters: {'n_estimators': 514, 'num_leaves': 26, 'learning_rate': 0.05628109945722505, 'subsample': 0.8184829137724084, 'colsample_bytree': 0.7092900825439995}. Best is trial 4 with value: 0.6610181511186155.
[I 2026-01-11 00:09:13,421] Trial 6 finished with value: 0.6816749683410721 and parameters: {'n_estimators': 443, 'num_leaves': 25, 'learning_rate': 0.015854643368675158, 'subsample': 0.8897771074506666, 'colsample_bytree': 0.8931264066149118}. Best is trial 6 with value: 0.6816749683410721.
[I 2026-01-11 00:09:14,300] Trial 7 finished with value: 0.6711051076403546 and parameters: {'n_estimators': 524, 'num_leaves': 29, 'learning_rate': 0.018790490260574548, 'subsample': 0.8368466053024314, 'colsample_bytree': 0.7880304987479203}. Best is trial 6 with value: 0.6816749683410721.
[I 2026-01-11 00:09:14,797] Trial 8 finished with value: 0.6922313212325876 and parameters: {'n_estimators': 248, 'num_leaves': 35, 'learning_rate': 0.013094966900369657, 'subsample': 0.8818640804157565, 'colsample_bytree': 0.7517559963200033}. Best is trial 8 with value: 0.6922313212325876.
[I 2026-01-11 00:09:15,573] Trial 9 finished with value: 0.6491616715913888 and parameters: {'n_estimators': 465, 'num_leaves': 29, 'learning_rate': 0.05680612190600298, 'subsample': 0.8093420558686559, 'colsample_bytree': 0.7369708911051054}. Best is trial 8 with value: 0.6922313212325876.
[I 2026-01-11 00:09:16,374] Trial 10 finished with value: 0.666289573659772 and parameters: {'n_estimators': 350, 'num_leaves': 41, 'learning_rate': 0.03311736949166599, 'subsample': 0.8909937467599877, 'colsample_bytree': 0.8303733101556356}. Best is trial 8 with value: 0.6922313212325876.
[I 2026-01-11 00:09:17,200] Trial 11 finished with value: 0.6879324609539891 and parameters: {'n_estimators': 380, 'num_leaves': 37, 'learning_rate': 0.010981227703002, 'subsample': 0.8963118581323058, 'colsample_bytree': 0.8963371826936029}. Best is trial 8 with value: 0.6922313212325876.
[I 2026-01-11 00:09:18,433] Trial 12 finished with value: 0.6795880118193331 and parameters: {'n_estimators': 587, 'num_leaves': 37, 'learning_rate': 0.012110311285307642, 'subsample': 0.8647430292312469, 'colsample_bytree': 0.8915839443678395}. Best is trial 8 with value: 0.6922313212325876.
[I 2026-01-11 00:09:19,137] Trial 13 finished with value: 0.6706728577458844 and parameters: {'n_estimators': 340, 'num_leaves': 37, 'learning_rate': 0.032087431857526064, 'subsample': 0.8644928101201926, 'colsample_bytree': 0.8474175474156693}. Best is trial 8 with value: 0.6922313212325876.
[I 2026-01-11 00:09:19,807] Trial 14 finished with value: 0.6744280287040946 and parameters: {'n_estimators': 289, 'num_leaves': 42, 'learning_rate': 0.02269263219331532, 'subsample': 0.857895413263893, 'colsample_bytree': 0.7695266860993165}. Best is trial 8 with value: 0.6922313212325876.
[I 2026-01-11 00:09:20,211] Trial 15 finished with value: 0.6685386238919375 and parameters: {'n_estimators': 213, 'num_leaves': 34, 'learning_rate': 0.044807131716047055, 'subsample': 0.8980992434928939, 'colsample_bytree': 0.8632856305553894}. Best is trial 8 with value: 0.6922313212325876.
[I 2026-01-11 00:09:21,128] Trial 16 finished with value: 0.6705208948923597 and parameters: {'n_estimators': 395, 'num_leaves': 43, 'learning_rate': 0.023850733448436176, 'subsample': 0.8472473098694974, 'colsample_bytree': 0.8219474056669265}. Best is trial 8 with value: 0.6922313212325876.
[I 2026-01-11 00:09:21,771] Trial 17 finished with value: 0.6905056986070071 and parameters: {'n_estimators': 311, 'num_leaves': 34, 'learning_rate': 0.010611433463270861, 'subsample': 0.7277625675105176, 'colsample_bytree': 0.8141230299574098}. Best is trial 8 with value: 0.6922313212325876.
[I 2026-01-11 00:09:22,349] Trial 18 finished with value: 0.6529810046433094 and parameters: {'n_estimators': 302, 'num_leaves': 33, 'learning_rate': 0.06786206969422147, 'subsample': 0.7241172138834286, 'colsample_bytree': 0.8100564652678953}. Best is trial 8 with value: 0.6922313212325876.
[I 2026-01-11 00:09:22,965] Trial 19 finished with value: 0.6578235542422963 and parameters: {'n_estimators': 247, 'num_leaves': 46, 'learning_rate': 0.09723428668438461, 'subsample': 0.7021978378487542, 'colsample_bytree': 0.7703043316266424}. Best is trial 8 with value: 0.6922313212325876.
[I 2026-01-11 00:09:23,521] Trial 20 finished with value: 0.6609607429295061 and parameters: {'n_estimators': 307, 'num_leaves': 32, 'learning_rate': 0.041106652649902285, 'subsample': 0.7533550114519743, 'colsample_bytree': 0.7009480239306178}. Best is trial 8 with value: 0.6922313212325876.
[I 2026-01-11 00:09:24,376] Trial 21 finished with value: 0.6860683832840861 and parameters: {'n_estimators': 384, 'num_leaves': 39, 'learning_rate': 0.010181773912930287, 'subsample': 0.8681074383456624, 'colsample_bytree': 0.8719299750391103}. Best is trial 8 with value: 0.6922313212325876.
[I 2026-01-11 00:09:25,044] Trial 22 finished with value: 0.6727429295061208 and parameters: {'n_estimators': 324, 'num_leaves': 36, 'learning_rate': 0.025501695235817204, 'subsample': 0.8784288723651785, 'colsample_bytree': 0.8722351780252766}. Best is trial 8 with value: 0.6922313212325876.
[I 2026-01-11 00:09:25,487] Trial 23 finished with value: 0.6948146897425074 and parameters: {'n_estimators': 239, 'num_leaves': 31, 'learning_rate': 0.010420065298147683, 'subsample': 0.78967381448854, 'colsample_bytree': 0.8084820898504602}. Best is trial 23 with value: 0.6948146897425074.
[I 2026-01-11 00:09:25,909] Trial 24 finished with value: 0.6772106373997467 and parameters: {'n_estimators': 235, 'num_leaves': 31, 'learning_rate': 0.028413276734322705, 'subsample': 0.7709124570555275, 'colsample_bytree': 0.8070461844044418}. Best is trial 23 with value: 0.6948146897425074.
[I 2026-01-11 00:09:26,319] Trial 25 finished with value: 0.6882262558041368 and parameters: {'n_estimators': 200, 'num_leaves': 34, 'learning_rate': 0.018835328318411344, 'subsample': 0.7012382038370896, 'colsample_bytree': 0.781510668772173}. Best is trial 23 with value: 0.6948146897425074.
[I 2026-01-11 00:09:26,751] Trial 26 finished with value: 0.6673566905867453 and parameters: {'n_estimators': 236, 'num_leaves': 30, 'learning_rate': 0.048612511121505386, 'subsample': 0.7290594577083103, 'colsample_bytree': 0.8181163556743234}. Best is trial 23 with value: 0.6948146897425074.
[I 2026-01-11 00:09:27,195] Trial 27 finished with value: 0.6906813001266358 and parameters: {'n_estimators': 271, 'num_leaves': 26, 'learning_rate': 0.015659556787839538, 'subsample': 0.7907321071500575, 'colsample_bytree': 0.7529110375634842}. Best is trial 23 with value: 0.6948146897425074.
[I 2026-01-11 00:09:27,576] Trial 28 finished with value: 0.6865918108906712 and parameters: {'n_estimators': 277, 'num_leaves': 21, 'learning_rate': 0.019643013554878783, 'subsample': 0.7915079540308119, 'colsample_bytree': 0.750008005603993}. Best is trial 23 with value: 0.6948146897425074.
[I 2026-01-11 00:09:27,951] Trial 29 finished with value: 0.6733541578725201 and parameters: {'n_estimators': 238, 'num_leaves': 27, 'learning_rate': 0.03816696341573818, 'subsample': 0.8023405850615966, 'colsample_bytree': 0.7226303028893024}. Best is trial 23 with value: 0.6948146897425074.
[I 2026-01-11 00:09:28,501] Trial 30 finished with value: 0.6715441114394258 and parameters: {'n_estimators': 343, 'num_leaves': 27, 'learning_rate': 0.029039146469574, 'subsample': 0.8316482034377575, 'colsample_bytree': 0.7532958029811396}. Best is trial 23 with value: 0.6948146897425074.
[I 2026-01-11 00:09:28,885] Trial 31 finished with value: 0.6948214436471085 and parameters: {'n_estimators': 261, 'num_leaves': 23, 'learning_rate': 0.014646537945817786, 'subsample': 0.7652689358057808, 'colsample_bytree': 0.8013910500322988}. Best is trial 31 with value: 0.6948214436471085.
[I 2026-01-11 00:09:29,271] Trial 32 finished with value: 0.6921165048543688 and parameters: {'n_estimators': 262, 'num_leaves': 23, 'learning_rate': 0.016312574556333972, 'subsample': 0.7702075538250837, 'colsample_bytree': 0.7982740300871655}. Best is trial 31 with value: 0.6948214436471085.
[I 2026-01-11 00:09:29,616] Trial 33 finished with value: 0.6858860278598564 and parameters: {'n_estimators': 253, 'num_leaves': 22, 'learning_rate': 0.023447136052087342, 'subsample': 0.7666632837569092, 'colsample_bytree': 0.7984767587377516}. Best is trial 31 with value: 0.6948214436471085.
[I 2026-01-11 00:09:29,915] Trial 34 finished with value: 0.6653440270156183 and parameters: {'n_estimators': 221, 'num_leaves': 23, 'learning_rate': 0.06639402717273304, 'subsample': 0.7567012459350727, 'colsample_bytree': 0.7998018761292701}. Best is trial 31 with value: 0.6948214436471085.
[I 2026-01-11 00:09:30,264] Trial 35 finished with value: 0.6905327142254115 and parameters: {'n_estimators': 266, 'num_leaves': 20, 'learning_rate': 0.016272066989954998, 'subsample': 0.78201507122947, 'colsample_bytree': 0.8360810817208394}. Best is trial 31 with value: 0.6948214436471085.
[I 2026-01-11 00:09:30,667] Trial 36 finished with value: 0.6808003376952302 and parameters: {'n_estimators': 289, 'num_leaves': 23, 'learning_rate': 0.028610011285695253, 'subsample': 0.7539603769082825, 'colsample_bytree': 0.7753393373545004}. Best is trial 31 with value: 0.6948214436471085.
[I 2026-01-11 00:09:30,937] Trial 37 finished with value: 0.6539772055719713 and parameters: {'n_estimators': 222, 'num_leaves': 20, 'learning_rate': 0.07990219365064871, 'subsample': 0.7412840363320172, 'colsample_bytree': 0.8459281865478705}. Best is trial 31 with value: 0.6948214436471085.
[I 2026-01-11 00:09:31,254] Trial 38 finished with value: 0.6956082735331364 and parameters: {'n_estimators': 200, 'num_leaves': 24, 'learning_rate': 0.01498668229652952, 'subsample': 0.8148977244565976, 'colsample_bytree': 0.7899532814463778}. Best is trial 38 with value: 0.6956082735331364.
[I 2026-01-11 00:09:31,555] Trial 39 finished with value: 0.6684271844660195 and parameters: {'n_estimators': 200, 'num_leaves': 25, 'learning_rate': 0.04918794364214415, 'subsample': 0.8189854685801671, 'colsample_bytree': 0.7623314013584638}. Best is trial 38 with value: 0.6956082735331364.
[I 2026-01-11 00:09:32,234] Trial 40 finished with value: 0.6748670325031659 and parameters: {'n_estimators': 419, 'num_leaves': 28, 'learning_rate': 0.02183273533702795, 'subsample': 0.8325524177760393, 'colsample_bytree': 0.7848593791760922}. Best is trial 38 with value: 0.6956082735331364.
[I 2026-01-11 00:09:32,617] Trial 41 finished with value: 0.6941190375685942 and parameters: {'n_estimators': 256, 'num_leaves': 24, 'learning_rate': 0.015322897174136534, 'subsample': 0.7778905013133558, 'colsample_bytree': 0.7970679281515088}. Best is trial 38 with value: 0.6956082735331364.
[I 2026-01-11 00:09:32,969] Trial 42 finished with value: 0.6966855213170114 and parameters: {'n_estimators': 227, 'num_leaves': 24, 'learning_rate': 0.014708543105723525, 'subsample': 0.8062701391994896, 'colsample_bytree': 0.7951034343364963}. Best is trial 42 with value: 0.6966855213170114.
[I 2026-01-11 00:09:33,319] Trial 43 finished with value: 0.6910493879273956 and parameters: {'n_estimators': 227, 'num_leaves': 25, 'learning_rate': 0.017062014768470808, 'subsample': 0.8067909658111466, 'colsample_bytree': 0.7927744296904011}. Best is trial 42 with value: 0.6966855213170114.
[I 2026-01-11 00:09:33,658] Trial 44 finished with value: 0.694345293372731 and parameters: {'n_estimators': 216, 'num_leaves': 25, 'learning_rate': 0.014026292207676658, 'subsample': 0.7842911777821684, 'colsample_bytree': 0.8277151276623602}. Best is trial 42 with value: 0.6966855213170114.
[I 2026-01-11 00:09:33,955] Trial 45 finished with value: 0.6809793161671591 and parameters: {'n_estimators': 212, 'num_leaves': 22, 'learning_rate': 0.032997005616426454, 'subsample': 0.7943023342873056, 'colsample_bytree': 0.8245181978056585}. Best is trial 42 with value: 0.6966855213170114.
[I 2026-01-11 00:09:34,300] Trial 46 finished with value: 0.690012663571127 and parameters: {'n_estimators': 201, 'num_leaves': 28, 'learning_rate': 0.020018683189472704, 'subsample': 0.8176774139416859, 'colsample_bytree': 0.8049758825759994}. Best is trial 42 with value: 0.6966855213170114.
[I 2026-01-11 00:09:34,727] Trial 47 finished with value: 0.6784938792739552 and parameters: {'n_estimators': 279, 'num_leaves': 26, 'learning_rate': 0.026632474574983134, 'subsample': 0.8010996645340036, 'colsample_bytree': 0.8329814738822364}. Best is trial 42 with value: 0.6966855213170114.
[I 2026-01-11 00:09:35,582] Trial 48 finished with value: 0.6841671591388772 and parameters: {'n_estimators': 491, 'num_leaves': 30, 'learning_rate': 0.01227303431298002, 'subsample': 0.812065587286574, 'colsample_bytree': 0.7810062396594988}. Best is trial 42 with value: 0.6966855213170114.

[I 2026-01-11 00:09:35,913] A new study created in memory with name: no-name-b3ea3d1f-55f6-48be-bda0-4ae014b3361a

[I 2026-01-11 00:09:35,910] Trial 49 finished with value: 0.6945614183199662 and parameters: {'n_estimators': 223, 'num_leaves': 24, 'learning_rate': 0.014200258294827017, 'subsample': 0.7875715256486073, 'colsample_bytree': 0.8137359668755015}. Best is trial 42 with value: 0.6966855213170114.

✓ Optimization completed!
  Best ROC-AUC: 0.6967
  Best parameters:
    n_estimators: 227
    num_leaves: 24
    learning_rate: 0.014708543105723525
    subsample: 0.8062701391994896
    colsample_bytree: 0.7951034343364963

================================================================================
HYPERPARAMETER TUNING - AdaBoost
================================================================================

✓ Using sample_weight to handle imbalance
  Class 0 weight: 0.590
  Class 1 weight: 3.291

✓ Starting Optuna optimization (40 trials)...
  Objective: Maximize ROC-AUC

  0%|          | 0/40 [00:00<?, ?it/s]

[I 2026-01-11 00:09:37,200] Trial 0 finished with value: 0.7106171380329254 and parameters: {'n_estimators': 181, 'learning_rate': 0.951207163345817}. Best is trial 0 with value: 0.7106171380329254.
[I 2026-01-11 00:09:39,223] Trial 1 finished with value: 0.7139535669058674 and parameters: {'n_estimators': 306, 'learning_rate': 0.6026718993550663}. Best is trial 1 with value: 0.7139535669058674.
[I 2026-01-11 00:09:39,959] Trial 2 finished with value: 0.7127412410299704 and parameters: {'n_estimators': 104, 'learning_rate': 0.16443457513284063}. Best is trial 1 with value: 0.7139535669058674.
[I 2026-01-11 00:09:40,426] Trial 3 finished with value: 0.7081992401857323 and parameters: {'n_estimators': 70, 'learning_rate': 0.8675143843171859}. Best is trial 1 with value: 0.7139535669058674.
[I 2026-01-11 00:09:42,172] Trial 4 finished with value: 0.7106542845082313 and parameters: {'n_estimators': 260, 'learning_rate': 0.710991852018085}. Best is trial 1 with value: 0.7139535669058674.
[I 2026-01-11 00:09:42,534] Trial 5 finished with value: 0.7080658505698607 and parameters: {'n_estimators': 57, 'learning_rate': 0.9702107536403743}. Best is trial 1 with value: 0.7139535669058674.
[I 2026-01-11 00:09:44,680] Trial 6 finished with value: 0.7174014352047278 and parameters: {'n_estimators': 342, 'learning_rate': 0.2202157195714934}. Best is trial 6 with value: 0.7174014352047278.
[I 2026-01-11 00:09:45,465] Trial 7 finished with value: 0.7129523005487548 and parameters: {'n_estimators': 113, 'learning_rate': 0.1915704647548995}. Best is trial 6 with value: 0.7174014352047278.
[I 2026-01-11 00:09:46,488] Trial 8 finished with value: 0.7171768678767412 and parameters: {'n_estimators': 156, 'learning_rate': 0.5295088673159155}. Best is trial 6 with value: 0.7174014352047278.
[I 2026-01-11 00:09:47,785] Trial 9 finished with value: 0.7172899957788095 and parameters: {'n_estimators': 201, 'learning_rate': 0.2983168487960615}. Best is trial 6 with value: 0.7174014352047278.
[I 2026-01-11 00:09:50,320] Trial 10 finished with value: 0.7074596876319122 and parameters: {'n_estimators': 393, 'learning_rate': 0.015937211126259176}. Best is trial 6 with value: 0.7174014352047278.
[I 2026-01-11 00:09:52,733] Trial 11 finished with value: 0.7174926129168424 and parameters: {'n_estimators': 362, 'learning_rate': 0.3300175907375913}. Best is trial 11 with value: 0.7174926129168424.
[I 2026-01-11 00:09:55,384] Trial 12 finished with value: 0.7169945124525116 and parameters: {'n_estimators': 394, 'learning_rate': 0.3635040930508199}. Best is trial 11 with value: 0.7174926129168424.
[I 2026-01-11 00:09:57,492] Trial 13 finished with value: 0.7185816800337695 and parameters: {'n_estimators': 333, 'learning_rate': 0.3985283631816061}. Best is trial 13 with value: 0.7185816800337695.
[I 2026-01-11 00:09:59,192] Trial 14 finished with value: 0.7193516251582946 and parameters: {'n_estimators': 270, 'learning_rate': 0.4070687789345023}. Best is trial 14 with value: 0.7193516251582946.
[I 2026-01-11 00:10:00,938] Trial 15 finished with value: 0.7174605318699874 and parameters: {'n_estimators': 257, 'learning_rate': 0.4455497124829996}. Best is trial 14 with value: 0.7193516251582946.
[I 2026-01-11 00:10:02,885] Trial 16 finished with value: 0.7138455044322499 and parameters: {'n_estimators': 306, 'learning_rate': 0.6101802832707559}. Best is trial 14 with value: 0.7193516251582946.
[I 2026-01-11 00:10:04,650] Trial 17 finished with value: 0.7171464753060363 and parameters: {'n_estimators': 267, 'learning_rate': 0.45524990159794043}. Best is trial 14 with value: 0.7193516251582946.
[I 2026-01-11 00:10:06,719] Trial 18 finished with value: 0.7093203883495145 and parameters: {'n_estimators': 313, 'learning_rate': 0.7699497377237832}. Best is trial 14 with value: 0.7193516251582946.
[I 2026-01-11 00:10:08,250] Trial 19 finished with value: 0.7099012241452088 and parameters: {'n_estimators': 239, 'learning_rate': 0.04466371655238177}. Best is trial 14 with value: 0.7193516251582946.
[I 2026-01-11 00:10:10,410] Trial 20 finished with value: 0.7138455044322498 and parameters: {'n_estimators': 342, 'learning_rate': 0.5542053099029007}. Best is trial 14 with value: 0.7193516251582946.
[I 2026-01-11 00:10:12,656] Trial 21 finished with value: 0.7176952300548755 and parameters: {'n_estimators': 355, 'learning_rate': 0.35986217694369105}. Best is trial 14 with value: 0.7193516251582946.
[I 2026-01-11 00:10:14,507] Trial 22 finished with value: 0.7185360911777121 and parameters: {'n_estimators': 288, 'learning_rate': 0.4187354253190594}. Best is trial 14 with value: 0.7193516251582946.
[I 2026-01-11 00:10:16,425] Trial 23 finished with value: 0.7169674968341072 and parameters: {'n_estimators': 294, 'learning_rate': 0.4501879782883536}. Best is trial 14 with value: 0.7193516251582946.
[I 2026-01-11 00:10:17,801] Trial 24 finished with value: 0.7171853102574925 and parameters: {'n_estimators': 218, 'learning_rate': 0.26387858614048637}. Best is trial 14 with value: 0.7193516251582946.
[I 2026-01-11 00:10:19,737] Trial 25 finished with value: 0.7157281553398057 and parameters: {'n_estimators': 294, 'learning_rate': 0.11650459175692512}. Best is trial 14 with value: 0.7193516251582946.
[I 2026-01-11 00:10:21,511] Trial 26 finished with value: 0.7182811312790206 and parameters: {'n_estimators': 273, 'learning_rate': 0.39901703124994253}. Best is trial 14 with value: 0.7193516251582946.
[I 2026-01-11 00:10:23,008] Trial 27 finished with value: 0.7116538623891937 and parameters: {'n_estimators': 232, 'learning_rate': 0.688649562047645}. Best is trial 14 with value: 0.7193516251582946.
[I 2026-01-11 00:10:25,182] Trial 28 finished with value: 0.7162904178978472 and parameters: {'n_estimators': 334, 'learning_rate': 0.49311629573249377}. Best is trial 14 with value: 0.7193516251582946.
[I 2026-01-11 00:10:27,637] Trial 29 finished with value: 0.7133490924440691 and parameters: {'n_estimators': 370, 'learning_rate': 0.5761515042400334}. Best is trial 14 with value: 0.7193516251582946.
[I 2026-01-11 00:10:28,707] Trial 30 finished with value: 0.7164423807513718 and parameters: {'n_estimators': 167, 'learning_rate': 0.2646659027795909}. Best is trial 14 with value: 0.7193516251582946.
[I 2026-01-11 00:10:30,692] Trial 31 finished with value: 0.7200540312368088 and parameters: {'n_estimators': 276, 'learning_rate': 0.40598089238987783}. Best is trial 31 with value: 0.7200540312368088.
[I 2026-01-11 00:10:32,510] Trial 32 finished with value: 0.7182017728999577 and parameters: {'n_estimators': 281, 'learning_rate': 0.3910996108161097}. Best is trial 31 with value: 0.7200540312368088.
[I 2026-01-11 00:10:34,596] Trial 33 finished with value: 0.7187555930772478 and parameters: {'n_estimators': 323, 'learning_rate': 0.4268712957271718}. Best is trial 31 with value: 0.7200540312368088.
[I 2026-01-11 00:10:36,609] Trial 34 finished with value: 0.7132460953989026 and parameters: {'n_estimators': 313, 'learning_rate': 0.6347211671033348}. Best is trial 31 with value: 0.7200540312368088.
[I 2026-01-11 00:10:38,821] Trial 35 finished with value: 0.7161874208526806 and parameters: {'n_estimators': 324, 'learning_rate': 0.4977072065757854}. Best is trial 31 with value: 0.7200540312368088.
[I 2026-01-11 00:10:40,506] Trial 36 finished with value: 0.7169945124525116 and parameters: {'n_estimators': 254, 'learning_rate': 0.29370647405642347}. Best is trial 31 with value: 0.7200540312368088.
[I 2026-01-11 00:10:43,039] Trial 37 finished with value: 0.7173305192064161 and parameters: {'n_estimators': 370, 'learning_rate': 0.1510372460852991}. Best is trial 31 with value: 0.7200540312368088.
[I 2026-01-11 00:10:44,630] Trial 38 finished with value: 0.70843056141832 and parameters: {'n_estimators': 244, 'learning_rate': 0.8377120866291334}. Best is trial 31 with value: 0.7200540312368088.
[I 2026-01-11 00:10:46,037] Trial 39 finished with value: 0.7167530603630224 and parameters: {'n_estimators': 217, 'learning_rate': 0.22050405930100458}. Best is trial 31 with value: 0.7200540312368088.

✓ Optimization completed!
  Best ROC-AUC: 0.7201
  Best parameters:
    n_estimators: 276
    learning_rate: 0.40598089238987783

================================================================================
TRAINING BASE ENSEMBLE MODELS
================================================================================

================================================================================
Training: XGBoost
================================================================================
  Running 5-fold cross-validation...

  Cross-Validation Results (mean ± std):
    Accuracy:  0.6805 ± 0.0260
    Precision: 0.2621 ± 0.0203
    Recall:    0.6000 ± 0.0188
    F1-Score:  0.3642 ± 0.0182
    ROC-AUC:   0.7085 ± 0.0192

  Test Set Performance:
    Accuracy:  0.6580
    Precision: 0.2395
    Recall:    0.5736
    F1-Score:  0.3379
    ROC-AUC:   0.6752

================================================================================
Training: LightGBM
================================================================================
  Running 5-fold cross-validation...

  Cross-Validation Results (mean ± std):
    Accuracy:  0.7206 ± 0.0185
    Precision: 0.2720 ± 0.0163
    Recall:    0.4951 ± 0.0213
    F1-Score:  0.3504 ± 0.0104
    ROC-AUC:   0.6967 ± 0.0215

  Test Set Performance:
    Accuracy:  0.6958
    Precision: 0.2389
    Recall:    0.4574
    F1-Score:  0.3138
    ROC-AUC:   0.6434

================================================================================
Training: AdaBoost
================================================================================
  Running 5-fold cross-validation...

  Cross-Validation Results (mean ± std):
    Accuracy:  0.6676 ± 0.0249
    Precision: 0.2594 ± 0.0182
    Recall:    0.6350 ± 0.0340
    F1-Score:  0.3678 ± 0.0187
    ROC-AUC:   0.7201 ± 0.0209

  Test Set Performance:
    Accuracy:  0.6545
    Precision: 0.2389
    Recall:    0.5814
    F1-Score:  0.3386
    ROC-AUC:   0.6779

================================================================================
CREATING STACKING ENSEMBLE
================================================================================

✓ Training stacking ensemble...
  Base estimators: 3
  Meta-learner: Logistic Regression
✓ Stacking ensemble trained successfully!

================================================================================
GENERATING VISUALIZATIONS
================================================================================

✓ ROC curves saved: roc_curves_comparison.png
✓ Confusion matrices saved: confusion_matrices.png

================================================================================
FEATURE IMPORTANCE & INTERPRETABILITY
================================================================================

================================================================================
Feature Importance Analysis - XGBoost
================================================================================

Top 10 Most Important Features:
  hypertension             : 0.2822
  age_group_code           : 0.2553
  pulse_pressure           : 0.1225
  cigarettes_per_day       : 0.0916
  glucose                  : 0.0669
  bmi                      : 0.0644
  total_cholesterol        : 0.0632
  heart_rate               : 0.0539

✓ Feature importance plot saved: feature_importance_xgboost.png

================================================================================
SHAP Analysis - XGBoost
================================================================================

✓ Creating SHAP explainer...
✓ Calculating SHAP values for 500 samples...
✓ SHAP summary plot saved: shap_summary_xgboost.png

Top 10 Features by SHAP Importance:
  age_group_code           : 0.3540
  cigarettes_per_day       : 0.2074
  pulse_pressure           : 0.2003
  hypertension             : 0.1295
  bmi                      : 0.0775
  total_cholesterol        : 0.0627
  glucose                  : 0.0523
  heart_rate               : 0.0309

================================================================================
Feature Importance Analysis - LightGBM
================================================================================

Top 10 Most Important Features:
  total_cholesterol        : 1033.0000
  bmi                      : 901.0000
  pulse_pressure           : 832.0000
  glucose                  : 814.0000
  heart_rate               : 773.0000
  cigarettes_per_day       : 427.0000
  age_group_code           : 362.0000
  hypertension             : 79.0000

✓ Feature importance plot saved: feature_importance_lightgbm.png

================================================================================
SHAP Analysis - LightGBM
================================================================================

✓ Creating SHAP explainer...
✓ Calculating SHAP values for 500 samples...
✓ SHAP summary plot saved: shap_summary_lightgbm.png

Top 10 Features by SHAP Importance:
  age_group_code           : 0.5406
  cigarettes_per_day       : 0.2778
  pulse_pressure           : 0.2343
  total_cholesterol        : 0.1380
  bmi                      : 0.1189
  hypertension             : 0.1159
  heart_rate               : 0.0948
  glucose                  : 0.0782

================================================================================
Feature Importance Analysis - AdaBoost
================================================================================

Top 10 Most Important Features:
  glucose                  : 0.3350
  age_group_code           : 0.2296
  total_cholesterol        : 0.1575
  pulse_pressure           : 0.1174
  cigarettes_per_day       : 0.0978
  hypertension             : 0.0352
  bmi                      : 0.0275
  heart_rate               : 0.0000

✓ Feature importance plot saved: feature_importance_adaboost.png

================================================================================
SHAP Analysis - AdaBoost
================================================================================

✓ Creating SHAP explainer...
✗ SHAP analysis failed: Model type not yet supported by TreeExplainer: <class 'sklearn.ensemble._weight_boosting.AdaBoostClassifier'>

================================================================================
LEARNING AND VALIDATION CURVES
================================================================================

================================================================================
Learning Curves - XGBoost
================================================================================
✓ Learning curves saved: learning_curves_xgboost.png

================================================================================
Validation Curve - XGBoost
================================================================================
✓ Validation curve saved: validation_curve_xgboost.png

================================================================================
Learning Curves - LightGBM
================================================================================
✓ Learning curves saved: learning_curves_lightgbm.png

================================================================================
Validation Curve - LightGBM
================================================================================
✓ Validation curve saved: validation_curve_lightgbm.png

================================================================================
Learning Curves - AdaBoost
================================================================================
✓ Learning curves saved: learning_curves_adaboost.png

================================================================================
Validation Curve - AdaBoost
================================================================================

[I 2026-01-11 00:11:01,787] A new study created in memory with name: no-name-c01cebb6-f2cf-4776-adb4-680fdbf5684a

✓ Validation curve saved: validation_curve_adaboost.png

================================================================================
CREATING MODEL COMPARISON TABLE
================================================================================

✓ Model comparison saved: model_comparison_boosting.csv

Model Comparison Table:
   Model  Accuracy  Precision   Recall  F1-Score  ROC-AUC
Stacking  0.654481   0.248466 0.627907  0.356044 0.687227
AdaBoost  0.654481   0.238854 0.581395  0.338600 0.677950
 XGBoost  0.658019   0.239482 0.573643  0.337900 0.675163
LightGBM  0.695755   0.238866 0.457364  0.313830 0.643400

================================================================================
CORONARY HEART DISEASE PREDICTION PROJECT
Advanced Models & Model Selection - Collaborator 5
================================================================================
Start Time: 2026-01-11 00:11:01
================================================================================
================================================================================
STEP 1: LOADING PRE-SPLIT DATA
================================================================================

✓ Loading training data from: ../data/processed\train_robust_scaled.csv
  Shape: (3390, 9)

✓ Loading test data from: ../data/processed\test_robust_scaled.csv
  Shape: (848, 9)

✓ Target column: TenYearCHD

✓ Data split information:
  Training set: (3390, 8)
  Test set: (848, 8)

✓ Feature consistency verified

✓ Training Set Class Distribution:
  Class 0 (No CHD): 2875 (84.81%)
  Class 1 (CHD): 515 (15.19%)
  Imbalance Ratio: 5.58:1

✓ Test Set Class Distribution:
  Class 0 (No CHD): 719 (84.79%)
  Class 1 (CHD): 129 (15.21%)
  Imbalance Ratio: 5.57:1

✓ No categorical variables found (all numeric)

✓ Features (8):
   1. bmi
   2. hypertension
   3. pulse_pressure
   4. cigarettes_per_day
   5. total_cholesterol
   6. glucose
   7. heart_rate
   8. age_group_code

================================================================================
HYPERPARAMETER TUNING - XGBoost
================================================================================

✓ Calculated scale_pos_weight: 5.58

✓ Starting Optuna optimization (50 trials)...
  Objective: Maximize ROC-AUC

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-01-11 00:11:02,479] Trial 0 finished with value: 0.6456395103419164 and parameters: {'n_estimators': 350, 'max_depth': 6, 'learning_rate': 0.07587945476302646, 'subsample': 0.8197316968394073, 'colsample_bytree': 0.7312037280884873}. Best is trial 0 with value: 0.6456395103419164.
[I 2026-01-11 00:11:02,760] Trial 1 finished with value: 0.6734250738708316 and parameters: {'n_estimators': 262, 'max_depth': 3, 'learning_rate': 0.08795585311974417, 'subsample': 0.8202230023486418, 'colsample_bytree': 0.8416145155592091}. Best is trial 1 with value: 0.6734250738708316.
[I 2026-01-11 00:11:03,217] Trial 2 finished with value: 0.657668214436471 and parameters: {'n_estimators': 208, 'max_depth': 6, 'learning_rate': 0.08491983767203796, 'subsample': 0.7424678221356552, 'colsample_bytree': 0.73636499344142}. Best is trial 1 with value: 0.6734250738708316.
[I 2026-01-11 00:11:03,670] Trial 3 finished with value: 0.6770417897847193 and parameters: {'n_estimators': 273, 'max_depth': 4, 'learning_rate': 0.05722807884690141, 'subsample': 0.7863890037284231, 'colsample_bytree': 0.7582458280396084}. Best is trial 3 with value: 0.6770417897847193.
[I 2026-01-11 00:11:04,230] Trial 4 finished with value: 0.6836403545799915 and parameters: {'n_estimators': 445, 'max_depth': 3, 'learning_rate': 0.03629301836816964, 'subsample': 0.7732723686587383, 'colsample_bytree': 0.7912139968434072}. Best is trial 4 with value: 0.6836403545799915.
[I 2026-01-11 00:11:04,853] Trial 5 finished with value: 0.6694504010130856 and parameters: {'n_estimators': 514, 'max_depth': 3, 'learning_rate': 0.05628109945722505, 'subsample': 0.8184829137724084, 'colsample_bytree': 0.7092900825439995}. Best is trial 4 with value: 0.6836403545799915.
[I 2026-01-11 00:11:05,338] Trial 6 finished with value: 0.6994681300126636 and parameters: {'n_estimators': 443, 'max_depth': 3, 'learning_rate': 0.015854643368675158, 'subsample': 0.8897771074506666, 'colsample_bytree': 0.8931264066149118}. Best is trial 6 with value: 0.6994681300126636.
[I 2026-01-11 00:11:05,989] Trial 7 finished with value: 0.688216124947235 and parameters: {'n_estimators': 524, 'max_depth': 4, 'learning_rate': 0.018790490260574548, 'subsample': 0.8368466053024314, 'colsample_bytree': 0.7880304987479203}. Best is trial 6 with value: 0.6994681300126636.
[I 2026-01-11 00:11:06,320] Trial 8 finished with value: 0.7059113550021106 and parameters: {'n_estimators': 248, 'max_depth': 4, 'learning_rate': 0.013094966900369657, 'subsample': 0.8818640804157565, 'colsample_bytree': 0.7517559963200033}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:11:06,962] Trial 9 finished with value: 0.6605690164626424 and parameters: {'n_estimators': 465, 'max_depth': 4, 'learning_rate': 0.05680612190600298, 'subsample': 0.8093420558686559, 'colsample_bytree': 0.7369708911051054}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:11:07,538] Trial 10 finished with value: 0.6724626424651752 and parameters: {'n_estimators': 350, 'max_depth': 5, 'learning_rate': 0.03311736949166599, 'subsample': 0.8909937467599877, 'colsample_bytree': 0.8303733101556356}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:11:08,154] Trial 11 finished with value: 0.6967766990291262 and parameters: {'n_estimators': 380, 'max_depth': 5, 'learning_rate': 0.010981227703002, 'subsample': 0.8963118581323058, 'colsample_bytree': 0.8963371826936029}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:11:08,780] Trial 12 finished with value: 0.6787471506964964 and parameters: {'n_estimators': 587, 'max_depth': 3, 'learning_rate': 0.02973925640254988, 'subsample': 0.8692884765349854, 'colsample_bytree': 0.8988011618189465}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:11:09,218] Trial 13 finished with value: 0.7031186154495568 and parameters: {'n_estimators': 296, 'max_depth': 4, 'learning_rate': 0.010413011005893648, 'subsample': 0.860482618301696, 'colsample_bytree': 0.8510074314100841}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:11:09,716] Trial 14 finished with value: 0.6707741663149008 and parameters: {'n_estimators': 289, 'max_depth': 5, 'learning_rate': 0.04514151169290863, 'subsample': 0.857895413263893, 'colsample_bytree': 0.8490601313653239}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:11:10,023] Trial 15 finished with value: 0.7001029970451668 and parameters: {'n_estimators': 213, 'max_depth': 4, 'learning_rate': 0.023351938164489116, 'subsample': 0.8543733335767764, 'colsample_bytree': 0.8188131070313829}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:11:10,443] Trial 16 finished with value: 0.6744381595609963 and parameters: {'n_estimators': 299, 'max_depth': 4, 'learning_rate': 0.04367948501124779, 'subsample': 0.8671855665744578, 'colsample_bytree': 0.8619157836706228}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:11:11,026] Trial 17 finished with value: 0.6977897847192909 and parameters: {'n_estimators': 324, 'max_depth': 5, 'learning_rate': 0.010599273764804039, 'subsample': 0.7277625675105176, 'colsample_bytree': 0.7714702251220459}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:11:11,363] Trial 18 finished with value: 0.6678868720979316 and parameters: {'n_estimators': 241, 'max_depth': 4, 'learning_rate': 0.06786206969422147, 'subsample': 0.8403740921446244, 'colsample_bytree': 0.8100564652678953}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:11:12,051] Trial 19 finished with value: 0.6408881384550442 and parameters: {'n_estimators': 393, 'max_depth': 5, 'learning_rate': 0.09723428668438461, 'subsample': 0.7021978378487542, 'colsample_bytree': 0.8629180257360286}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:11:12,494] Trial 20 finished with value: 0.6954731954411143 and parameters: {'n_estimators': 328, 'max_depth': 4, 'learning_rate': 0.02274258174871161, 'subsample': 0.876603754483263, 'colsample_bytree': 0.7009480239306178}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:11:12,775] Trial 21 finished with value: 0.6985023216547066 and parameters: {'n_estimators': 202, 'max_depth': 4, 'learning_rate': 0.024274307691962267, 'subsample': 0.8479057628120712, 'colsample_bytree': 0.8153898347779356}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:11:13,137] Trial 22 finished with value: 0.6972021950189955 and parameters: {'n_estimators': 237, 'max_depth': 4, 'learning_rate': 0.026348332542640115, 'subsample': 0.8542828376388392, 'colsample_bytree': 0.8266404628456154}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:11:13,460] Trial 23 finished with value: 0.7011093288307302 and parameters: {'n_estimators': 234, 'max_depth': 4, 'learning_rate': 0.017787654107243523, 'subsample': 0.8791467587819954, 'colsample_bytree': 0.7708148758426131}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:11:13,861] Trial 24 finished with value: 0.676153651329675 and parameters: {'n_estimators': 244, 'max_depth': 5, 'learning_rate': 0.040132817457210895, 'subsample': 0.8761284264482079, 'colsample_bytree': 0.7668750708322092}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:11:14,332] Trial 25 finished with value: 0.6984516673701984 and parameters: {'n_estimators': 297, 'max_depth': 4, 'learning_rate': 0.01635713338614355, 'subsample': 0.8973416298412669, 'colsample_bytree': 0.7558039557597273}. Best is trial 8 with value: 0.7059113550021106.
[I 2026-01-11 00:11:14,656] Trial 26 finished with value: 0.7091295905445335 and parameters: {'n_estimators': 264, 'max_depth': 3, 'learning_rate': 0.010743139598731657, 'subsample': 0.834669340930887, 'colsample_bytree': 0.7816329682425044}. Best is trial 26 with value: 0.7091295905445335.
[I 2026-01-11 00:11:15,005] Trial 27 finished with value: 0.7095685943436049 and parameters: {'n_estimators': 317, 'max_depth': 3, 'learning_rate': 0.010955295681655963, 'subsample': 0.8377011536124971, 'colsample_bytree': 0.7928838677943963}. Best is trial 27 with value: 0.7095685943436049.
[I 2026-01-11 00:11:15,355] Trial 28 finished with value: 0.6965774588433937 and parameters: {'n_estimators': 329, 'max_depth': 3, 'learning_rate': 0.03027023712446687, 'subsample': 0.7889826034359546, 'colsample_bytree': 0.8008616799342849}. Best is trial 27 with value: 0.7095685943436049.
[I 2026-01-11 00:11:15,803] Trial 29 finished with value: 0.6860042211903756 and parameters: {'n_estimators': 364, 'max_depth': 3, 'learning_rate': 0.05123211282079642, 'subsample': 0.831105809042793, 'colsample_bytree': 0.7226303028893024}. Best is trial 27 with value: 0.7095685943436049.
[I 2026-01-11 00:11:16,428] Trial 30 finished with value: 0.6842785985647952 and parameters: {'n_estimators': 268, 'max_depth': 6, 'learning_rate': 0.018718426780795744, 'subsample': 0.7989949096553459, 'colsample_bytree': 0.7852999902036104}. Best is trial 27 with value: 0.7095685943436049.
[I 2026-01-11 00:11:16,783] Trial 31 finished with value: 0.7098117349092444 and parameters: {'n_estimators': 312, 'max_depth': 3, 'learning_rate': 0.01041555142712366, 'subsample': 0.8265026055068294, 'colsample_bytree': 0.7470733046160744}. Best is trial 31 with value: 0.7098117349092444.
[I 2026-01-11 00:11:17,153] Trial 32 finished with value: 0.7077990713381174 and parameters: {'n_estimators': 332, 'max_depth': 3, 'learning_rate': 0.014864418904025088, 'subsample': 0.8185350856517829, 'colsample_bytree': 0.7455423783924988}. Best is trial 31 with value: 0.7098117349092444.
[I 2026-01-11 00:11:17,597] Trial 33 finished with value: 0.7022304769945125 and parameters: {'n_estimators': 419, 'max_depth': 3, 'learning_rate': 0.020076514996409743, 'subsample': 0.82361598892196, 'colsample_bytree': 0.7443786803004346}. Best is trial 31 with value: 0.7098117349092444.
[I 2026-01-11 00:11:17,935] Trial 34 finished with value: 0.680209371042634 and parameters: {'n_estimators': 314, 'max_depth': 3, 'learning_rate': 0.06639402717273304, 'subsample': 0.7685850332917236, 'colsample_bytree': 0.7241314979302085}. Best is trial 31 with value: 0.7098117349092444.
[I 2026-01-11 00:11:18,302] Trial 35 finished with value: 0.6979417475728156 and parameters: {'n_estimators': 350, 'max_depth': 3, 'learning_rate': 0.027878018004045213, 'subsample': 0.8057447507329569, 'colsample_bytree': 0.7788899528477934}. Best is trial 31 with value: 0.7098117349092444.
[I 2026-01-11 00:11:18,666] Trial 36 finished with value: 0.7072655128746307 and parameters: {'n_estimators': 278, 'max_depth': 3, 'learning_rate': 0.014672885946710826, 'subsample': 0.8196878926295227, 'colsample_bytree': 0.8007305246909497}. Best is trial 31 with value: 0.7098117349092444.
[I 2026-01-11 00:11:19,066] Trial 37 finished with value: 0.6662152807091599 and parameters: {'n_estimators': 371, 'max_depth': 3, 'learning_rate': 0.08062933146367443, 'subsample': 0.8268728853747789, 'colsample_bytree': 0.7621231047281358}. Best is trial 31 with value: 0.7098117349092444.
[I 2026-01-11 00:11:19,358] Trial 38 finished with value: 0.7005149852258337 and parameters: {'n_estimators': 265, 'max_depth': 3, 'learning_rate': 0.03564640918689765, 'subsample': 0.7776016894687576, 'colsample_bytree': 0.7450668141483597}. Best is trial 31 with value: 0.7098117349092444.
[I 2026-01-11 00:11:19,816] Trial 39 finished with value: 0.7015956099620093 and parameters: {'n_estimators': 413, 'max_depth': 3, 'learning_rate': 0.02079811337925825, 'subsample': 0.8430633421523637, 'colsample_bytree': 0.727525787445404}. Best is trial 31 with value: 0.7098117349092444.
[I 2026-01-11 00:11:20,247] Trial 40 finished with value: 0.7084102997045167 and parameters: {'n_estimators': 342, 'max_depth': 3, 'learning_rate': 0.014549253771309896, 'subsample': 0.8117457601406398, 'colsample_bytree': 0.7152395042890346}. Best is trial 31 with value: 0.7098117349092444.
[I 2026-01-11 00:11:20,631] Trial 41 finished with value: 0.7087344871253694 and parameters: {'n_estimators': 343, 'max_depth': 3, 'learning_rate': 0.015322897174136534, 'subsample': 0.812465197179679, 'colsample_bytree': 0.7186325078380088}. Best is trial 31 with value: 0.7098117349092444.
[I 2026-01-11 00:11:21,031] Trial 42 finished with value: 0.7091667370198397 and parameters: {'n_estimators': 350, 'max_depth': 3, 'learning_rate': 0.010345696154716205, 'subsample': 0.7980696596922362, 'colsample_bytree': 0.713668432240117}. Best is trial 31 with value: 0.7098117349092444.
[I 2026-01-11 00:11:21,378] Trial 43 finished with value: 0.7098252427184466 and parameters: {'n_estimators': 309, 'max_depth': 3, 'learning_rate': 0.010515379562200595, 'subsample': 0.7938172952836617, 'colsample_bytree': 0.7107856782593096}. Best is trial 43 with value: 0.7098252427184466.
[I 2026-01-11 00:11:21,734] Trial 44 finished with value: 0.710487125369354 and parameters: {'n_estimators': 317, 'max_depth': 3, 'learning_rate': 0.010303039133269954, 'subsample': 0.7931683466305235, 'colsample_bytree': 0.7043506757405738}. Best is trial 44 with value: 0.710487125369354.
[I 2026-01-11 00:11:22,131] Trial 45 finished with value: 0.7099299282397636 and parameters: {'n_estimators': 307, 'max_depth': 3, 'learning_rate': 0.010299987260913177, 'subsample': 0.7943526271771272, 'colsample_bytree': 0.7006081635545736}. Best is trial 44 with value: 0.710487125369354.
[I 2026-01-11 00:11:22,525] Trial 46 finished with value: 0.7032536935415787 and parameters: {'n_estimators': 309, 'max_depth': 3, 'learning_rate': 0.022480433544231147, 'subsample': 0.760719844298136, 'colsample_bytree': 0.7005173678700647}. Best is trial 44 with value: 0.710487125369354.
[I 2026-01-11 00:11:22,885] Trial 47 finished with value: 0.6979755170958211 and parameters: {'n_estimators': 311, 'max_depth': 3, 'learning_rate': 0.03230562067162567, 'subsample': 0.7522088715789241, 'colsample_bytree': 0.7358342336706536}. Best is trial 44 with value: 0.710487125369354.
[I 2026-01-11 00:11:23,398] Trial 48 finished with value: 0.7024027015618405 and parameters: {'n_estimators': 491, 'max_depth': 3, 'learning_rate': 0.01856652424446534, 'subsample': 0.7874355001740965, 'colsample_bytree': 0.7074073752289582}. Best is trial 44 with value: 0.710487125369354.

[I 2026-01-11 00:11:23,722] A new study created in memory with name: no-name-d4d3e807-820f-4933-b794-64c85fdb499d

[I 2026-01-11 00:11:23,720] Trial 49 finished with value: 0.7029463908822287 and parameters: {'n_estimators': 285, 'max_depth': 3, 'learning_rate': 0.026921786603406883, 'subsample': 0.7820278342387397, 'colsample_bytree': 0.7310381798666995}. Best is trial 44 with value: 0.710487125369354.

✓ Optimization completed!
  Best ROC-AUC: 0.7105
  Best parameters:
    n_estimators: 317
    max_depth: 3
    learning_rate: 0.010303039133269954
    subsample: 0.7931683466305235
    colsample_bytree: 0.7043506757405738

================================================================================
HYPERPARAMETER TUNING - LightGBM
================================================================================

✓ Calculated scale_pos_weight: 5.58

✓ Starting Optuna optimization (50 trials)...
  Objective: Maximize ROC-AUC

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-01-11 00:11:24,645] Trial 0 finished with value: 0.6509244406922752 and parameters: {'n_estimators': 350, 'num_leaves': 49, 'learning_rate': 0.07587945476302646, 'subsample': 0.8197316968394073, 'colsample_bytree': 0.7312037280884873}. Best is trial 0 with value: 0.6509244406922752.
[I 2026-01-11 00:11:24,974] Trial 1 finished with value: 0.650775854791051 and parameters: {'n_estimators': 262, 'num_leaves': 21, 'learning_rate': 0.08795585311974417, 'subsample': 0.8202230023486418, 'colsample_bytree': 0.8416145155592091}. Best is trial 0 with value: 0.6509244406922752.
[I 2026-01-11 00:11:25,554] Trial 2 finished with value: 0.6551591388771634 and parameters: {'n_estimators': 208, 'num_leaves': 50, 'learning_rate': 0.08491983767203796, 'subsample': 0.7424678221356552, 'colsample_bytree': 0.73636499344142}. Best is trial 2 with value: 0.6551591388771634.
[I 2026-01-11 00:11:26,036] Trial 3 finished with value: 0.6563241874208526 and parameters: {'n_estimators': 273, 'num_leaves': 29, 'learning_rate': 0.05722807884690141, 'subsample': 0.7863890037284231, 'colsample_bytree': 0.7582458280396084}. Best is trial 3 with value: 0.6563241874208526.
[I 2026-01-11 00:11:26,797] Trial 4 finished with value: 0.6597146475306037 and parameters: {'n_estimators': 445, 'num_leaves': 24, 'learning_rate': 0.03629301836816964, 'subsample': 0.7732723686587383, 'colsample_bytree': 0.7912139968434072}. Best is trial 4 with value: 0.6597146475306037.
[I 2026-01-11 00:11:27,634] Trial 5 finished with value: 0.6543250316589277 and parameters: {'n_estimators': 514, 'num_leaves': 26, 'learning_rate': 0.05628109945722505, 'subsample': 0.8184829137724084, 'colsample_bytree': 0.7092900825439995}. Best is trial 4 with value: 0.6597146475306037.
[I 2026-01-11 00:11:28,372] Trial 6 finished with value: 0.680411988180667 and parameters: {'n_estimators': 443, 'num_leaves': 25, 'learning_rate': 0.015854643368675158, 'subsample': 0.8897771074506666, 'colsample_bytree': 0.8931264066149118}. Best is trial 6 with value: 0.680411988180667.
[I 2026-01-11 00:11:29,267] Trial 7 finished with value: 0.6737391304347826 and parameters: {'n_estimators': 524, 'num_leaves': 29, 'learning_rate': 0.018790490260574548, 'subsample': 0.8368466053024314, 'colsample_bytree': 0.7880304987479203}. Best is trial 6 with value: 0.680411988180667.
[I 2026-01-11 00:11:29,764] Trial 8 finished with value: 0.693710426340228 and parameters: {'n_estimators': 248, 'num_leaves': 35, 'learning_rate': 0.013094966900369657, 'subsample': 0.8818640804157565, 'colsample_bytree': 0.7517559963200033}. Best is trial 8 with value: 0.693710426340228.
[I 2026-01-11 00:11:30,559] Trial 9 finished with value: 0.6533896158716758 and parameters: {'n_estimators': 465, 'num_leaves': 29, 'learning_rate': 0.05680612190600298, 'subsample': 0.8093420558686559, 'colsample_bytree': 0.7369708911051054}. Best is trial 8 with value: 0.693710426340228.
[I 2026-01-11 00:11:31,367] Trial 10 finished with value: 0.660639932460954 and parameters: {'n_estimators': 350, 'num_leaves': 41, 'learning_rate': 0.03311736949166599, 'subsample': 0.8909937467599877, 'colsample_bytree': 0.8303733101556356}. Best is trial 8 with value: 0.693710426340228.
[I 2026-01-11 00:11:32,238] Trial 11 finished with value: 0.6852883073026592 and parameters: {'n_estimators': 380, 'num_leaves': 37, 'learning_rate': 0.010981227703002, 'subsample': 0.8963118581323058, 'colsample_bytree': 0.8963371826936029}. Best is trial 8 with value: 0.693710426340228.
[I 2026-01-11 00:11:33,506] Trial 12 finished with value: 0.6761165048543689 and parameters: {'n_estimators': 587, 'num_leaves': 37, 'learning_rate': 0.012110311285307642, 'subsample': 0.8647430292312469, 'colsample_bytree': 0.8915839443678395}. Best is trial 8 with value: 0.693710426340228.
[I 2026-01-11 00:11:34,229] Trial 13 finished with value: 0.6666171380329253 and parameters: {'n_estimators': 340, 'num_leaves': 37, 'learning_rate': 0.032087431857526064, 'subsample': 0.8644928101201926, 'colsample_bytree': 0.8474175474156693}. Best is trial 8 with value: 0.693710426340228.
[I 2026-01-11 00:11:34,944] Trial 14 finished with value: 0.6784094554664415 and parameters: {'n_estimators': 289, 'num_leaves': 42, 'learning_rate': 0.02269263219331532, 'subsample': 0.857895413263893, 'colsample_bytree': 0.7695266860993165}. Best is trial 8 with value: 0.693710426340228.
[I 2026-01-11 00:11:35,355] Trial 15 finished with value: 0.6711321232587589 and parameters: {'n_estimators': 213, 'num_leaves': 34, 'learning_rate': 0.044807131716047055, 'subsample': 0.8980992434928939, 'colsample_bytree': 0.8632856305553894}. Best is trial 8 with value: 0.693710426340228.
[I 2026-01-11 00:11:36,427] Trial 16 finished with value: 0.6663300970873787 and parameters: {'n_estimators': 395, 'num_leaves': 43, 'learning_rate': 0.023850733448436176, 'subsample': 0.8472473098694974, 'colsample_bytree': 0.8219474056669265}. Best is trial 8 with value: 0.693710426340228.
[I 2026-01-11 00:11:37,075] Trial 17 finished with value: 0.6901274799493458 and parameters: {'n_estimators': 311, 'num_leaves': 34, 'learning_rate': 0.010611433463270861, 'subsample': 0.7277625675105176, 'colsample_bytree': 0.8141230299574098}. Best is trial 8 with value: 0.693710426340228.
[I 2026-01-11 00:11:37,670] Trial 18 finished with value: 0.6502051498522584 and parameters: {'n_estimators': 302, 'num_leaves': 33, 'learning_rate': 0.06786206969422147, 'subsample': 0.7241172138834286, 'colsample_bytree': 0.8100564652678953}. Best is trial 8 with value: 0.693710426340228.
[I 2026-01-11 00:11:38,299] Trial 19 finished with value: 0.654412832418742 and parameters: {'n_estimators': 247, 'num_leaves': 46, 'learning_rate': 0.09723428668438461, 'subsample': 0.7021978378487542, 'colsample_bytree': 0.7703043316266424}. Best is trial 8 with value: 0.693710426340228.
[I 2026-01-11 00:11:38,887] Trial 20 finished with value: 0.6651211481637822 and parameters: {'n_estimators': 307, 'num_leaves': 32, 'learning_rate': 0.041106652649902285, 'subsample': 0.7533550114519743, 'colsample_bytree': 0.7009480239306178}. Best is trial 8 with value: 0.693710426340228.
[I 2026-01-11 00:11:39,763] Trial 21 finished with value: 0.6877365977205573 and parameters: {'n_estimators': 384, 'num_leaves': 39, 'learning_rate': 0.010181773912930287, 'subsample': 0.8681074383456624, 'colsample_bytree': 0.8719299750391103}. Best is trial 8 with value: 0.693710426340228.
[I 2026-01-11 00:11:40,489] Trial 22 finished with value: 0.6716791895314479 and parameters: {'n_estimators': 324, 'num_leaves': 39, 'learning_rate': 0.025501695235817204, 'subsample': 0.875587559488785, 'colsample_bytree': 0.8705566424385562}. Best is trial 8 with value: 0.693710426340228.
[I 2026-01-11 00:11:40,936] Trial 23 finished with value: 0.6955306036302236 and parameters: {'n_estimators': 239, 'num_leaves': 31, 'learning_rate': 0.010412175659456244, 'subsample': 0.8381664301819819, 'colsample_bytree': 0.8068646281099502}. Best is trial 23 with value: 0.6955306036302236.
[I 2026-01-11 00:11:41,359] Trial 24 finished with value: 0.6784905023216548 and parameters: {'n_estimators': 235, 'num_leaves': 31, 'learning_rate': 0.028413276734322705, 'subsample': 0.8344884690330143, 'colsample_bytree': 0.8058202756090669}. Best is trial 23 with value: 0.6955306036302236.
[I 2026-01-11 00:11:41,769] Trial 25 finished with value: 0.6864702406078514 and parameters: {'n_estimators': 200, 'num_leaves': 35, 'learning_rate': 0.018835328318411344, 'subsample': 0.7815104699178844, 'colsample_bytree': 0.781510668772173}. Best is trial 23 with value: 0.6955306036302236.
[I 2026-01-11 00:11:42,171] Trial 26 finished with value: 0.6660700717602364 and parameters: {'n_estimators': 236, 'num_leaves': 30, 'learning_rate': 0.048612511121505386, 'subsample': 0.7946153512031772, 'colsample_bytree': 0.8181163556743234}. Best is trial 23 with value: 0.6955306036302236.
[I 2026-01-11 00:11:42,737] Trial 27 finished with value: 0.6851262135922329 and parameters: {'n_estimators': 271, 'num_leaves': 36, 'learning_rate': 0.015659556787839538, 'subsample': 0.7075402630016802, 'colsample_bytree': 0.7514213473740741}. Best is trial 23 with value: 0.6955306036302236.
[I 2026-01-11 00:11:43,196] Trial 28 finished with value: 0.6654791051076403 and parameters: {'n_estimators': 291, 'num_leaves': 27, 'learning_rate': 0.03792937632479417, 'subsample': 0.7614862788700912, 'colsample_bytree': 0.8034705130428134}. Best is trial 23 with value: 0.6955306036302236.
[I 2026-01-11 00:11:44,029] Trial 29 finished with value: 0.6714124102997046 and parameters: {'n_estimators': 327, 'num_leaves': 46, 'learning_rate': 0.027480466233753956, 'subsample': 0.8433438152801837, 'colsample_bytree': 0.7226303028893024}. Best is trial 23 with value: 0.6955306036302236.
[I 2026-01-11 00:11:44,482] Trial 30 finished with value: 0.6843292528493035 and parameters: {'n_estimators': 237, 'num_leaves': 33, 'learning_rate': 0.02052896343948857, 'subsample': 0.8794347994360143, 'colsample_bytree': 0.7532958029811396}. Best is trial 23 with value: 0.6955306036302236.
[I 2026-01-11 00:11:45,343] Trial 31 finished with value: 0.6879797382861967 and parameters: {'n_estimators': 381, 'num_leaves': 39, 'learning_rate': 0.010403676337873674, 'subsample': 0.87578392882198, 'colsample_bytree': 0.8539625884061947}. Best is trial 23 with value: 0.6955306036302236.
[I 2026-01-11 00:11:46,176] Trial 32 finished with value: 0.6805605740818911 and parameters: {'n_estimators': 372, 'num_leaves': 39, 'learning_rate': 0.014989487532778296, 'subsample': 0.8528894666562963, 'colsample_bytree': 0.8417901416228439}. Best is trial 23 with value: 0.6955306036302236.
[I 2026-01-11 00:11:46,757] Trial 33 finished with value: 0.643809202195019 and parameters: {'n_estimators': 425, 'num_leaves': 22, 'learning_rate': 0.06896722220662779, 'subsample': 0.8293464823120782, 'colsample_bytree': 0.8545549211103594}. Best is trial 23 with value: 0.6955306036302236.
[I 2026-01-11 00:11:47,267] Trial 34 finished with value: 0.6834985225833685 and parameters: {'n_estimators': 255, 'num_leaves': 35, 'learning_rate': 0.019134705988503108, 'subsample': 0.8764238133175013, 'colsample_bytree': 0.832139343098589}. Best is trial 23 with value: 0.6955306036302236.
[I 2026-01-11 00:11:47,760] Trial 35 finished with value: 0.6958142676234698 and parameters: {'n_estimators': 279, 'num_leaves': 31, 'learning_rate': 0.010210606246783308, 'subsample': 0.7351825253223762, 'colsample_bytree': 0.7942743766432236}. Best is trial 35 with value: 0.6958142676234698.
[I 2026-01-11 00:11:48,188] Trial 36 finished with value: 0.6716960742929506 and parameters: {'n_estimators': 273, 'num_leaves': 27, 'learning_rate': 0.03070186157580402, 'subsample': 0.7328976089505967, 'colsample_bytree': 0.7937343173576826}. Best is trial 35 with value: 0.6958142676234698.
[I 2026-01-11 00:11:48,612] Trial 37 finished with value: 0.692849303503588 and parameters: {'n_estimators': 222, 'num_leaves': 31, 'learning_rate': 0.016054331412006816, 'subsample': 0.7188869511021828, 'colsample_bytree': 0.7718244101942757}. Best is trial 35 with value: 0.6958142676234698.
[I 2026-01-11 00:11:49,012] Trial 38 finished with value: 0.6911338117349093 and parameters: {'n_estimators': 219, 'num_leaves': 31, 'learning_rate': 0.016895250343999156, 'subsample': 0.7166339743305711, 'colsample_bytree': 0.7772211698276089}. Best is trial 35 with value: 0.6958142676234698.
[I 2026-01-11 00:11:49,378] Trial 39 finished with value: 0.6883410721823553 and parameters: {'n_estimators': 222, 'num_leaves': 28, 'learning_rate': 0.022514132108758217, 'subsample': 0.7453969547528817, 'colsample_bytree': 0.7624763479899821}. Best is trial 35 with value: 0.6958142676234698.
[I 2026-01-11 00:11:49,724] Trial 40 finished with value: 0.6574385816800339 and parameters: {'n_estimators': 259, 'num_leaves': 23, 'learning_rate': 0.08121910567689544, 'subsample': 0.8108339634908518, 'colsample_bytree': 0.7470836970442732}. Best is trial 35 with value: 0.6958142676234698.
[I 2026-01-11 00:11:50,091] Trial 41 finished with value: 0.6919206416209371 and parameters: {'n_estimators': 201, 'num_leaves': 32, 'learning_rate': 0.016432448758160804, 'subsample': 0.7174172354077873, 'colsample_bytree': 0.7808321794694251}. Best is trial 35 with value: 0.6958142676234698.
[I 2026-01-11 00:11:50,469] Trial 42 finished with value: 0.6932275221612495 and parameters: {'n_estimators': 201, 'num_leaves': 31, 'learning_rate': 0.015263137521439462, 'subsample': 0.7148129565091997, 'colsample_bytree': 0.7943004122700463}. Best is trial 35 with value: 0.6958142676234698.
[I 2026-01-11 00:11:50,809] Trial 43 finished with value: 0.6963951034191642 and parameters: {'n_estimators': 227, 'num_leaves': 25, 'learning_rate': 0.014529861600643904, 'subsample': 0.7409826728201568, 'colsample_bytree': 0.7970824504672817}. Best is trial 43 with value: 0.6963951034191642.
[I 2026-01-11 00:11:51,234] Trial 44 finished with value: 0.6946289573659772 and parameters: {'n_estimators': 280, 'num_leaves': 25, 'learning_rate': 0.013802551558365716, 'subsample': 0.7375296473607762, 'colsample_bytree': 0.7934941874994146}. Best is trial 43 with value: 0.6963951034191642.
[I 2026-01-11 00:11:51,581] Trial 45 finished with value: 0.6846264246517517 and parameters: {'n_estimators': 280, 'num_leaves': 20, 'learning_rate': 0.024362839311624133, 'subsample': 0.7399452445167595, 'colsample_bytree': 0.8264915887247101}. Best is trial 43 with value: 0.6963951034191642.
[I 2026-01-11 00:11:51,998] Trial 46 finished with value: 0.6966010975094977 and parameters: {'n_estimators': 262, 'num_leaves': 25, 'learning_rate': 0.013852246085013837, 'subsample': 0.7670254305252129, 'colsample_bytree': 0.7975000197829812}. Best is trial 46 with value: 0.6966010975094977.
[I 2026-01-11 00:11:52,392] Trial 47 finished with value: 0.657810046433094 and parameters: {'n_estimators': 265, 'num_leaves': 25, 'learning_rate': 0.06290627015067128, 'subsample': 0.7655001316370711, 'colsample_bytree': 0.7971578575508897}. Best is trial 46 with value: 0.6966010975094977.
[I 2026-01-11 00:11:53,132] Trial 48 finished with value: 0.6571042634022795 and parameters: {'n_estimators': 491, 'num_leaves': 25, 'learning_rate': 0.03465044746961289, 'subsample': 0.7760995594851596, 'colsample_bytree': 0.7831120353916591}. Best is trial 46 with value: 0.6966010975094977.

[I 2026-01-11 00:11:53,560] A new study created in memory with name: no-name-b1a64c11-3d3a-4b36-9415-c695e60986dc

[I 2026-01-11 00:11:53,557] Trial 49 finished with value: 0.6824043900379906 and parameters: {'n_estimators': 297, 'num_leaves': 23, 'learning_rate': 0.02156103523697868, 'subsample': 0.7551793229192952, 'colsample_bytree': 0.7897151268783897}. Best is trial 46 with value: 0.6966010975094977.

✓ Optimization completed!
  Best ROC-AUC: 0.6966
  Best parameters:
    n_estimators: 262
    num_leaves: 25
    learning_rate: 0.013852246085013837
    subsample: 0.7670254305252129
    colsample_bytree: 0.7975000197829812

================================================================================
HYPERPARAMETER TUNING - AdaBoost
================================================================================

✓ Using sample_weight to handle imbalance
  Class 0 weight: 0.590
  Class 1 weight: 3.291

✓ Starting Optuna optimization (40 trials)...
  Objective: Maximize ROC-AUC

  0%|          | 0/40 [00:00<?, ?it/s]

[I 2026-01-11 00:11:54,808] Trial 0 finished with value: 0.7106171380329254 and parameters: {'n_estimators': 181, 'learning_rate': 0.951207163345817}. Best is trial 0 with value: 0.7106171380329254.
[I 2026-01-11 00:11:56,869] Trial 1 finished with value: 0.7139535669058674 and parameters: {'n_estimators': 306, 'learning_rate': 0.6026718993550663}. Best is trial 1 with value: 0.7139535669058674.
[I 2026-01-11 00:11:57,554] Trial 2 finished with value: 0.7127412410299704 and parameters: {'n_estimators': 104, 'learning_rate': 0.16443457513284063}. Best is trial 1 with value: 0.7139535669058674.
[I 2026-01-11 00:11:58,004] Trial 3 finished with value: 0.7081992401857323 and parameters: {'n_estimators': 70, 'learning_rate': 0.8675143843171859}. Best is trial 1 with value: 0.7139535669058674.
[I 2026-01-11 00:11:59,821] Trial 4 finished with value: 0.7106542845082313 and parameters: {'n_estimators': 260, 'learning_rate': 0.710991852018085}. Best is trial 1 with value: 0.7139535669058674.
[I 2026-01-11 00:12:00,231] Trial 5 finished with value: 0.7080658505698607 and parameters: {'n_estimators': 57, 'learning_rate': 0.9702107536403743}. Best is trial 1 with value: 0.7139535669058674.
[I 2026-01-11 00:12:02,518] Trial 6 finished with value: 0.7174014352047278 and parameters: {'n_estimators': 342, 'learning_rate': 0.2202157195714934}. Best is trial 6 with value: 0.7174014352047278.
[I 2026-01-11 00:12:03,268] Trial 7 finished with value: 0.7129523005487548 and parameters: {'n_estimators': 113, 'learning_rate': 0.1915704647548995}. Best is trial 6 with value: 0.7174014352047278.
[I 2026-01-11 00:12:04,278] Trial 8 finished with value: 0.7172157028281976 and parameters: {'n_estimators': 156, 'learning_rate': 0.5295088673159155}. Best is trial 6 with value: 0.7174014352047278.
[I 2026-01-11 00:12:05,583] Trial 9 finished with value: 0.7173254537779654 and parameters: {'n_estimators': 201, 'learning_rate': 0.2983168487960615}. Best is trial 6 with value: 0.7174014352047278.
[I 2026-01-11 00:12:08,207] Trial 10 finished with value: 0.7074596876319122 and parameters: {'n_estimators': 393, 'learning_rate': 0.015937211126259176}. Best is trial 6 with value: 0.7174014352047278.
[I 2026-01-11 00:12:10,565] Trial 11 finished with value: 0.7175246939636978 and parameters: {'n_estimators': 362, 'learning_rate': 0.3300175907375913}. Best is trial 11 with value: 0.7175246939636978.
[I 2026-01-11 00:12:13,196] Trial 12 finished with value: 0.7170164626424652 and parameters: {'n_estimators': 394, 'learning_rate': 0.3635040930508199}. Best is trial 11 with value: 0.7175246939636978.
[I 2026-01-11 00:12:15,464] Trial 13 finished with value: 0.7186036302237231 and parameters: {'n_estimators': 333, 'learning_rate': 0.3985283631816061}. Best is trial 13 with value: 0.7186036302237231.
[I 2026-01-11 00:12:17,286] Trial 14 finished with value: 0.7193870831574504 and parameters: {'n_estimators': 270, 'learning_rate': 0.4070687789345023}. Best is trial 14 with value: 0.7193870831574504.
[I 2026-01-11 00:12:19,030] Trial 15 finished with value: 0.7174926129168424 and parameters: {'n_estimators': 257, 'learning_rate': 0.4455497124829996}. Best is trial 14 with value: 0.7193870831574504.
[I 2026-01-11 00:12:21,010] Trial 16 finished with value: 0.7138455044322499 and parameters: {'n_estimators': 306, 'learning_rate': 0.6101802832707559}. Best is trial 14 with value: 0.7193870831574504.
[I 2026-01-11 00:12:22,809] Trial 17 finished with value: 0.7171853102574925 and parameters: {'n_estimators': 267, 'learning_rate': 0.45524990159794043}. Best is trial 14 with value: 0.7193870831574504.
[I 2026-01-11 00:12:24,754] Trial 18 finished with value: 0.7093271422541156 and parameters: {'n_estimators': 313, 'learning_rate': 0.7699497377237832}. Best is trial 14 with value: 0.7193870831574504.
[I 2026-01-11 00:12:26,343] Trial 19 finished with value: 0.7099012241452088 and parameters: {'n_estimators': 239, 'learning_rate': 0.04466371655238177}. Best is trial 14 with value: 0.7193870831574504.
[I 2026-01-11 00:12:28,525] Trial 20 finished with value: 0.7138792739552553 and parameters: {'n_estimators': 342, 'learning_rate': 0.5542053099029007}. Best is trial 14 with value: 0.7193870831574504.
[I 2026-01-11 00:12:30,829] Trial 21 finished with value: 0.7177138032925284 and parameters: {'n_estimators': 355, 'learning_rate': 0.35986217694369105}. Best is trial 14 with value: 0.7193870831574504.
[I 2026-01-11 00:12:32,665] Trial 22 finished with value: 0.7185647952722667 and parameters: {'n_estimators': 288, 'learning_rate': 0.4187354253190594}. Best is trial 14 with value: 0.7193870831574504.
[I 2026-01-11 00:12:34,668] Trial 23 finished with value: 0.7169995778809624 and parameters: {'n_estimators': 294, 'learning_rate': 0.4501879782883536}. Best is trial 14 with value: 0.7193870831574504.
[I 2026-01-11 00:12:36,063] Trial 24 finished with value: 0.7172207682566484 and parameters: {'n_estimators': 218, 'learning_rate': 0.26387858614048637}. Best is trial 14 with value: 0.7193870831574504.
[I 2026-01-11 00:12:37,952] Trial 25 finished with value: 0.7157281553398057 and parameters: {'n_estimators': 294, 'learning_rate': 0.11650459175692512}. Best is trial 14 with value: 0.7193870831574504.
[I 2026-01-11 00:12:39,745] Trial 26 finished with value: 0.7183064584212746 and parameters: {'n_estimators': 273, 'learning_rate': 0.39901703124994253}. Best is trial 14 with value: 0.7193870831574504.
[I 2026-01-11 00:12:41,231] Trial 27 finished with value: 0.7116572393414942 and parameters: {'n_estimators': 232, 'learning_rate': 0.688649562047645}. Best is trial 14 with value: 0.7193870831574504.
[I 2026-01-11 00:12:43,529] Trial 28 finished with value: 0.716325875897003 and parameters: {'n_estimators': 334, 'learning_rate': 0.49311629573249377}. Best is trial 14 with value: 0.7193870831574504.
[I 2026-01-11 00:12:45,917] Trial 29 finished with value: 0.7133862389193751 and parameters: {'n_estimators': 370, 'learning_rate': 0.5761515042400334}. Best is trial 14 with value: 0.7193870831574504.
[I 2026-01-11 00:12:47,010] Trial 30 finished with value: 0.7164812157028282 and parameters: {'n_estimators': 167, 'learning_rate': 0.2646659027795909}. Best is trial 14 with value: 0.7193870831574504.
[I 2026-01-11 00:12:48,815] Trial 31 finished with value: 0.7200726044744618 and parameters: {'n_estimators': 276, 'learning_rate': 0.40598089238987783}. Best is trial 31 with value: 0.7200726044744618.
[I 2026-01-11 00:12:50,626] Trial 32 finished with value: 0.7182237230899113 and parameters: {'n_estimators': 281, 'learning_rate': 0.3910996108161097}. Best is trial 31 with value: 0.7200726044744618.
[I 2026-01-11 00:12:52,785] Trial 33 finished with value: 0.7187674124102996 and parameters: {'n_estimators': 323, 'learning_rate': 0.4268712957271718}. Best is trial 31 with value: 0.7200726044744618.
[I 2026-01-11 00:12:54,821] Trial 34 finished with value: 0.7132460953989026 and parameters: {'n_estimators': 313, 'learning_rate': 0.6347211671033348}. Best is trial 31 with value: 0.7200726044744618.
[I 2026-01-11 00:12:56,854] Trial 35 finished with value: 0.7162161249472352 and parameters: {'n_estimators': 324, 'learning_rate': 0.4977072065757854}. Best is trial 31 with value: 0.7200726044744618.
[I 2026-01-11 00:12:58,470] Trial 36 finished with value: 0.7170299704516673 and parameters: {'n_estimators': 254, 'learning_rate': 0.29370647405642347}. Best is trial 31 with value: 0.7200726044744618.
[I 2026-01-11 00:13:00,815] Trial 37 finished with value: 0.7173457154917686 and parameters: {'n_estimators': 370, 'learning_rate': 0.1510372460852991}. Best is trial 31 with value: 0.7200726044744618.
[I 2026-01-11 00:13:02,362] Trial 38 finished with value: 0.70843056141832 and parameters: {'n_estimators': 244, 'learning_rate': 0.8377120866291334}. Best is trial 31 with value: 0.7200726044744618.
[I 2026-01-11 00:13:03,794] Trial 39 finished with value: 0.7167530603630224 and parameters: {'n_estimators': 217, 'learning_rate': 0.22050405930100458}. Best is trial 31 with value: 0.7200726044744618.

✓ Optimization completed!
  Best ROC-AUC: 0.7201
  Best parameters:
    n_estimators: 276
    learning_rate: 0.40598089238987783

================================================================================
TRAINING BASE ENSEMBLE MODELS
================================================================================

================================================================================
Training: XGBoost
================================================================================
  Running 5-fold cross-validation...

  Cross-Validation Results (mean ± std):
    Accuracy:  0.6805 ± 0.0260
    Precision: 0.2621 ± 0.0203
    Recall:    0.6000 ± 0.0188
    F1-Score:  0.3642 ± 0.0182
    ROC-AUC:   0.7085 ± 0.0192

  Test Set Performance:
    Accuracy:  0.6580
    Precision: 0.2395
    Recall:    0.5736
    F1-Score:  0.3379
    ROC-AUC:   0.6752

================================================================================
Training: LightGBM
================================================================================
  Running 5-fold cross-validation...

  Cross-Validation Results (mean ± std):
    Accuracy:  0.7233 ± 0.0174
    Precision: 0.2710 ± 0.0173
    Recall:    0.4816 ± 0.0200
    F1-Score:  0.3463 ± 0.0136
    ROC-AUC:   0.6966 ± 0.0192

  Test Set Performance:
    Accuracy:  0.7028
    Precision: 0.2448
    Recall:    0.4574
    F1-Score:  0.3189
    ROC-AUC:   0.6491

================================================================================
Training: AdaBoost
================================================================================
  Running 5-fold cross-validation...

  Cross-Validation Results (mean ± std):
    Accuracy:  0.6676 ± 0.0249
    Precision: 0.2594 ± 0.0182
    Recall:    0.6350 ± 0.0340
    F1-Score:  0.3678 ± 0.0187
    ROC-AUC:   0.7201 ± 0.0209

  Test Set Performance:
    Accuracy:  0.6545
    Precision: 0.2389
    Recall:    0.5814
    F1-Score:  0.3386
    ROC-AUC:   0.6779

================================================================================
CREATING STACKING ENSEMBLE
================================================================================

✓ Training stacking ensemble...
  Base estimators: 3
  Meta-learner: Logistic Regression
✓ Stacking ensemble trained successfully!

================================================================================
GENERATING VISUALIZATIONS
================================================================================

✓ ROC curves saved: roc_curves_comparison.png
✓ Confusion matrices saved: confusion_matrices.png

================================================================================
FEATURE IMPORTANCE & INTERPRETABILITY
================================================================================

================================================================================
Feature Importance Analysis - XGBoost
================================================================================

Top 10 Most Important Features:
  hypertension             : 0.2822
  age_group_code           : 0.2553
  pulse_pressure           : 0.1225
  cigarettes_per_day       : 0.0916
  glucose                  : 0.0669
  bmi                      : 0.0644
  total_cholesterol        : 0.0632
  heart_rate               : 0.0539

✓ Feature importance plot saved: feature_importance_xgboost.png

================================================================================
SHAP Analysis - XGBoost
================================================================================

✓ Creating SHAP explainer...
✓ Calculating SHAP values for 500 samples...
✓ SHAP summary plot saved: shap_summary_xgboost.png

Top 10 Features by SHAP Importance:
  age_group_code           : 0.3540
  cigarettes_per_day       : 0.2074
  pulse_pressure           : 0.2003
  hypertension             : 0.1295
  bmi                      : 0.0775
  total_cholesterol        : 0.0627
  glucose                  : 0.0523
  heart_rate               : 0.0309

================================================================================
Feature Importance Analysis - LightGBM
================================================================================

Top 10 Most Important Features:
  total_cholesterol        : 1239.0000
  bmi                      : 1124.0000
  pulse_pressure           : 1045.0000
  glucose                  : 947.0000
  heart_rate               : 927.0000
  cigarettes_per_day       : 505.0000
  age_group_code           : 405.0000
  hypertension             : 96.0000

✓ Feature importance plot saved: feature_importance_lightgbm.png

================================================================================
SHAP Analysis - LightGBM
================================================================================

✓ Creating SHAP explainer...
✓ Calculating SHAP values for 500 samples...
✓ SHAP summary plot saved: shap_summary_lightgbm.png

Top 10 Features by SHAP Importance:
  age_group_code           : 0.5543
  cigarettes_per_day       : 0.2920
  pulse_pressure           : 0.2318
  total_cholesterol        : 0.1489
  hypertension             : 0.1292
  bmi                      : 0.1216
  heart_rate               : 0.1014
  glucose                  : 0.0810

================================================================================
Feature Importance Analysis - AdaBoost
================================================================================

Top 10 Most Important Features:
  glucose                  : 0.3350
  age_group_code           : 0.2296
  total_cholesterol        : 0.1575
  pulse_pressure           : 0.1174
  cigarettes_per_day       : 0.0978
  hypertension             : 0.0352
  bmi                      : 0.0275
  heart_rate               : 0.0000

✓ Feature importance plot saved: feature_importance_adaboost.png

================================================================================
SHAP Analysis - AdaBoost
================================================================================

✓ Creating SHAP explainer...
✗ SHAP analysis failed: Model type not yet supported by TreeExplainer: <class 'sklearn.ensemble._weight_boosting.AdaBoostClassifier'>

================================================================================
LEARNING AND VALIDATION CURVES
================================================================================

================================================================================
Learning Curves - XGBoost
================================================================================
✓ Learning curves saved: learning_curves_xgboost.png

================================================================================
Validation Curve - XGBoost
================================================================================
✓ Validation curve saved: validation_curve_xgboost.png

================================================================================
Learning Curves - LightGBM
================================================================================
✓ Learning curves saved: learning_curves_lightgbm.png

================================================================================
Validation Curve - LightGBM
================================================================================
✓ Validation curve saved: validation_curve_lightgbm.png

================================================================================
Learning Curves - AdaBoost
================================================================================
✓ Learning curves saved: learning_curves_adaboost.png

================================================================================
Validation Curve - AdaBoost
================================================================================
✓ Validation curve saved: validation_curve_adaboost.png

================================================================================
CREATING MODEL COMPARISON TABLE
================================================================================

✓ Model comparison saved: model_comparison_boosting.csv

Model Comparison Table:
   Model  Accuracy  Precision   Recall  F1-Score  ROC-AUC
Stacking  0.650943   0.243077 0.612403  0.348018 0.686505
AdaBoost  0.654481   0.238854 0.581395  0.338600 0.677950
 XGBoost  0.658019   0.239482 0.573643  0.337900 0.675163
LightGBM  0.702830   0.244813 0.457364  0.318919 0.649060

In [4]:
comparison_boosting = "model_comparison_boosting.csv"
boosting_comparison_df = load_dataset(os.path.join(DATA_DIR, comparison_boosting))
boosting_comparison_df['Dataset_version'] ='standard_scaled'
boosting_comparison_df.loc[boosting_comparison_df['Model'] == 'XGBoost', 'Imbalance_method'] = 'scale_pos_weight'
boosting_comparison_df.loc[boosting_comparison_df['Model'] == 'LightGBM', 'Imbalance_method'] = 'scale_pos_weight'
boosting_comparison_df.loc[boosting_comparison_df['Model'] == 'AdaBoost', 'Imbalance_method'] = 'sample_weight'
boosting_comparison_df.loc[boosting_comparison_df['Model'] == 'Stacking', 'Imbalance_method'] = 'class_weight (meta-learner)'

display(boosting_comparison_df)

,Model,Accuracy,Precision,Recall,F1-Score,ROC-AUC,Dataset_version,Imbalance_method
0,Stacking,0.847877,0.000000,0.000000,0.00000,0.686203,standard_scaled,class_weight (meta-learner)
1,AdaBoost,0.847877,0.000000,0.000000,0.00000,0.679507,standard_scaled,none
2,XGBoost,0.658019,0.239482,0.573643,0.33790,0.675163,standard_scaled,scale_pos_weight
3,LightGBM,0.695755,0.238866,0.457364,0.31383,0.643400,standard_scaled,scale_pos_weight

In [5]:
traditional_comparison_df = traditional_comparison_df.rename(
    columns={
        "dataset_version": "Dataset_version",
        "model_name": "Model",
        "imbalance_method": "Imbalance_method",
        "test_accuracy": "Accuracy",
        "test_precision": "Precision",
        "test_recall": "Recall",
        "test_f1": "F1-Score",
        "test_roc_auc": "ROC-AUC"
    }
)

traditional_relevant = traditional_comparison_df[["Dataset_version", "Model", "Imbalance_method", "Accuracy", "Precision", "Recall", "F1-Score", "ROC-AUC"]]
boosting_comparison_df = boosting_comparison_df[["Dataset_version", "Model", "Imbalance_method", "Accuracy", "Precision", "Recall", "F1-Score", "ROC-AUC"]]

In [6]:
comparison_models = pd.concat([traditional_relevant, boosting_comparison_df], ignore_index=True)
display(comparison_models.sort_values("ROC-AUC", ascending=False).head(30))

,Dataset_version,Model,Imbalance_method,Accuracy,Precision,Recall,F1-Score,ROC-AUC
0,standard_scaled,svm,class_weight,0.669811,0.252459,0.596899,0.354839,0.689712
1,unscaled,svm,class_weight,0.668632,0.251634,0.596899,0.354023,0.689712
2,robust_scaled,svm,class_weight,0.668632,0.251634,0.596899,0.354023,0.689588
7,robust_scaled,svm,smote,0.650943,0.244648,0.620155,0.350877,0.688887
8,robust_scaled,svm,smote+class_weight,0.650943,0.244648,0.620155,0.350877,0.688887
5,standard_scaled,svm,smote,0.650943,0.244648,0.620155,0.350877,0.687637
6,standard_scaled,svm,smote+class_weight,0.650943,0.244648,0.620155,0.350877,0.687637
3,unscaled,svm,smote,0.650943,0.244648,0.620155,0.350877,0.687615
4,unscaled,svm,smote+class_weight,0.650943,0.244648,0.620155,0.350877,0.687615
49,robust_scaled,logistic_regression,none,0.846698,0.454545,0.038760,0.071429,0.687141
47,unscaled,logistic_regression,none,0.846698,0.454545,0.038760,0.071429,0.687108
48,standard_scaled,logistic_regression,none,0.846698,0.454545,0.038760,0.071429,0.687108
13,standard_scaled,logistic_regression,class_weight,0.654481,0.240506,0.589147,0.341573,0.686785
9,robust_scaled,logistic_regression,class_weight,0.656840,0.242038,0.589147,0.343115,0.686785
12,unscaled,logistic_regression,class_weight,0.654481,0.240506,0.589147,0.341573,0.686785
54,standard_scaled,Stacking,class_weight (meta-learner),0.847877,0.000000,0.000000,0.000000,0.686203
11,robust_scaled,logistic_regression,smote+class_weight,0.646226,0.238532,0.604651,0.342105,0.686160
10,robust_scaled,logistic_regression,smote,0.646226,0.238532,0.604651,0.342105,0.686160
14,unscaled,logistic_regression,smote,0.642689,0.234756,0.596899,0.336980,0.684812
15,unscaled,logistic_regression,smote+class_weight,0.642689,0.234756,0.596899,0.336980,0.684812
16,standard_scaled,logistic_regression,smote,0.642689,0.234756,0.596899,0.336980,0.684812
17,standard_scaled,logistic_regression,smote+class_weight,0.642689,0.234756,0.596899,0.336980,0.684812
55,standard_scaled,AdaBoost,none,0.847877,0.000000,0.000000,0.000000,0.679507
56,standard_scaled,XGBoost,scale_pos_weight,0.658019,0.239482,0.573643,0.337900,0.675163
53,robust_scaled,svm,none,0.847877,0.000000,0.000000,0.000000,0.669761
51,standard_scaled,random_forest,none,0.849057,0.571429,0.031008,0.058824,0.664456
52,robust_scaled,random_forest,none,0.849057,0.571429,0.031008,0.058824,0.663454
50,unscaled,random_forest,none,0.849057,0.571429,0.031008,0.058824,0.663260
32,standard_scaled,random_forest,class_weight,0.787736,0.278261,0.248062,0.262295,0.662591
31,robust_scaled,random_forest,class_weight,0.788915,0.284483,0.255814,0.269388,0.661998

## Model Selection:

NameError: name 'all_results' is not defined